package com.ccclubs.pub.orm.mapper;

import com.ccclubs.pub.orm.model.SrvDict;
import com.ccclubs.pub.orm.model.SrvDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrvDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    long countByExample(SrvDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    int deleteByExample(SrvDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    int insert(SrvDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    int insertSelective(SrvDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    List<SrvDict> selectByExample(SrvDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    SrvDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrvDict record, @Param("example") SrvDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrvDict record, @Param("example") SrvDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrvDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrvDict record);
}