package com.ccclubs.pub.orm.mapper;

import com.ccclubs.pub.orm.model.VerUpgradeRecord;
import com.ccclubs.pub.orm.model.VerUpgradeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerUpgradeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade_record
     *
     * @mbg.generated
     */
    long countByExample(VerUpgradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade_record
     *
     * @mbg.generated
     */
    int deleteByExample(VerUpgradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade_record
     *
     * @mbg.generated
     */
    int insert(VerUpgradeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade_record
     *
     * @mbg.generated
     */
    int insertSelective(VerUpgradeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade_record
     *
     * @mbg.generated
     */
    List<VerUpgradeRecord> selectByExample(VerUpgradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VerUpgradeRecord record, @Param("example") VerUpgradeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VerUpgradeRecord record, @Param("example") VerUpgradeRecordExample example);
}