package com.ccclubs.pub.orm.mapper;

import com.ccclubs.pub.orm.model.VerUpPrecondition;
import com.ccclubs.pub.orm.model.VerUpPreconditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerUpPreconditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    long countByExample(VerUpPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    int deleteByExample(VerUpPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    int insert(VerUpPrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    int insertSelective(VerUpPrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    List<VerUpPrecondition> selectByExample(VerUpPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    VerUpPrecondition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VerUpPrecondition record, @Param("example") VerUpPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VerUpPrecondition record, @Param("example") VerUpPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VerUpPrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_precondition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VerUpPrecondition record);
}