package com.ccclubs.pub.orm.mapper;

import com.ccclubs.pub.orm.model.VerUpgrade;
import com.ccclubs.pub.orm.model.VerUpgradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerUpgradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    long countByExample(VerUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    int deleteByExample(VerUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    int insert(VerUpgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    int insertSelective(VerUpgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    List<VerUpgrade> selectByExample(VerUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    VerUpgrade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VerUpgrade record, @Param("example") VerUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VerUpgrade record, @Param("example") VerUpgradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VerUpgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VerUpgrade record);
}