server:
  port: 11116

spring:
  redis:
    host: r-bp10b96658d427c4.redis.rds.aliyuncs.com
    password: zgjrB7aUk83plwCpyrEk
    database: 7
    pool:
      maxIdle: 8
      minIdle: 0
      maxActive: 64
      maxWait: -1
  data:
    mongodb:
      uri: mongodb://vc_user:0c33a326e0c943d3b5f9eabc73d09d2f@dds-bp1810d170d2e1742.mongodb.rds.aliyuncs.com:3717,dds-bp1810d170d2e1741.mongodb.rds.aliyuncs.com:3717/vcloud_db?replicaSet=mgset-4431147&maxPoolSize=50


dubbo:
  scan:
    annotationPackage: com.ccclubs
  application:
    name: cmd-engine-srv
  registry:
    address: 10.47.97.150:2181,10.25.4.117:2182,10.24.24.188:2183
    protocol: zookeeper
    port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false
  monitor:
    protocol: registry

#MQ topic
mq:
  topic: terminal
  car: car
  protocol: protocol
  #应用日志
  log:
    showSource: true

#阿里云 MQ Consumer 配置
ons:
  producerId: PID_terminal_ser
  consumerId: CID_ser_operation
  accessKey: M6dHCyKyKYUCNbW4
  secretKey: k6gOSH3dNJjFYze4CuxbBWS1PWqvVk
  consumeThreadNums: 30
  topic: ser
  # Tag
  expression: MQTT_03||MQTT_05||MQTT_06||MQTT_0F||MQTT_10||MQTT_46||MQTT_47||MQTT_48||MQTT_49||MQTT_50||MQTT_6F||MQTT_F0

druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://rm-bp1ly42351i7096mj.mysql.rds.aliyuncs.com:3306/ccclubs_data_center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: tmp_user
    password: RsyKWvf4U0bHSuzTfZTG
  initialSize: 2
  maxActive: 50
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: