server:
  port: 12005

spring:
  redis:
    host: 10.24.24.241
    database: 7
  data:
    mongodb:
      host: 10.24.24.241
      port: 3717
      username: dba
      password: office_97
      database: vc_remote
      authenticationDatabase: vc_remote

dubbo:
  scan:
    annotationPackage: com.ccclubs.engine,com.ccclubs.frm.redis,com.ccclubs.frm.mqtt,com.ccclubs.frm.ons,com.ccclubs.frm.mongodb,com.ccclubs.mongo,com.ccclubs.common
  application:
    name: cmd-engine-srv-test
  registry:
    address: 10.122.72.180:2181,10.122.72.180:2182,10.122.72.180:2183
    protocol: zookeeper
    port: 20665
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20665
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false
#  monitor:
#    protocol: registry

#MQ topic
mq:
  topic: terminal
  car: car
  protocol: protocol
  #应用日志
  log:
    showSource: true

#阿里云 MQ Consumer 配置
ons:
  producerId: PID_terminal_ser
  consumerId: CID_ser_operation_test
  accessKey: M6dHCyKyKYUCNbW4
  secretKey: k6gOSH3dNJjFYze4CuxbBWS1PWqvVk
  consumeThreadNums: 10
  topic: ser_test
  # Tag
  expression: MQTT_03||MQTT_05||MQTT_06||MQTT_0F||MQTT_10||MQTT_46||MQTT_47||MQTT_48||MQTT_49||MQTT_50||MQTT_6F||MQTT_F0

druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://10.132.27.108:3306/vc_data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: alpha_user
    password: 3CvQMOiJFihcVnOLOw6J
  initialSize: 2
  maxActive: 4
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: