server:
  port: 11114

spring:
  redis: 
    host: r-bp10b96658d427c4.redis.rds.aliyuncs.com
    password: zgjrB7aUk83plwCpyrEk
    database: 7
    pool:
      maxIdle: 8
      minIdle: 0
      maxActive: 64
      maxWait: -1
  data:
    mongodb:
      uri: mongodb://vc_user:0c33a326e0c943d3b5f9eabc73d09d2f@dds-bp1810d170d2e1742.mongodb.rds.aliyuncs.com:3717,dds-bp1810d170d2e1741.mongodb.rds.aliyuncs.com:3717/vcloud_db?replicaSet=mgset-4431147&maxPoolSize=50

dubbo:
  scan:
    annotationPackage: com.ccclubs.command,com.ccclubs.frm.mongodb,com.ccclubs.frm.redis,com.ccclubs.mongodb,com.ccclubs.common
  application:
    name: command-srv
  registry:
    address: 10.47.97.150:2181,10.25.4.117:2182,10.24.24.188:2183
    protocol: zookeeper
    port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false
  monitor:
    protocol: registry
druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://rm-bp1ly42351i7096mj.mysql.rds.aliyuncs.com:3306/ccclubs_data_center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: tmp_user
    password: RsyKWvf4U0bHSuzTfZTG
  initialSize: 2
  maxActive: 50
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  filters:

mqttAliyun:
  #阿里云 mqtt broker 地址
  host: tcp://mqtt.cn-hangzhou.aliyuncs.com
  #阿里云 mqtt broker 端口
  port: 1883
  #阿里云 mqClient ID 前缀
  preId: GID_pro
  #阿里云用户名
  userName: M6dHCyKyKYUCNbW4
  #阿里云密码
  pwd: 2u0w1llRPSxKeNSZDq95jQAE95c=
  #是否记录上行记录
  logUpDown: true

mqttOwn:
  #自有 mqtt broker 地址
  host: tcp://10.252.93.25
  #自有 mqtt broker 端口
  port: 27736
  #mqClient ID 前缀
  preId: command
  #用户名
  userName: qsxiaogang
  #密码
  pwd: 513387369
  #是否记录上行记录
  logUpDown: true

#配置业务参数
#指令码与指令ID对照 TODO
command:
  #获取状态
  cmdMap[1]: 76
  #开门
  cmdMap[2]: 69
  cmdMap[52]: 28
  #锁门
  cmdMap[3]: 70
  cmdMap[53]: 1
  #允许启动
  cmdMap[4]: 71
  cmdMap[54]: 2
  #禁止启动
  cmdMap[5]: 72
  cmdMap[55]: 3
  #鸣笛
  cmdMap[6]: 73
  cmdMap[56]: 17
  #开门并允许启动
  cmdMap[7]: 74
  #锁门并禁止启动
  cmdMap[8]: 75
  #初始化
  cmdMap[9]: 4
  #发动机启动
  cmdMap[10]: 25
  #发动机停止
  cmdMap[11]: 26
  #终端重启
  cmdMap[12]: 9
  #取车（远程取车）
  cmdMap[13]: 6
  #还车（远程还车）
  cmdMap[14]: 7
  #新系统支持的终端版本号
  #富士康
  supportVersionMap[0]: 1327
  #中导
  supportVersionMap[1]: 1027
  #慧翰
  supportVersionMap[2]: 0
  #通领
  supportVersionMap[3]: 1072