server:
  port: 8081
spring:
  http: 
    encoding: 
      charset: UTF-8
      enable: true
      force: true
name: zkj
api:
  security:
      apiId: appKey
      appId: '{cipher}AIB6DsANDSW8Ehs0L8EcMJe7cjxfzwOP1+onlXhQryApv/JJod3syv1exOHUw/DEBaNdzkb1BqR01PdXs3+mKNxQUNtaY8xqztz3hiJx1S963Ke8pB5yOKwdJ0cDWO11k5Fi16QCCcB6Gxy3ASjLBPpK75iZwQx/paWhSkdCj7Tm7BjE+wnEEYtNTIB/YjXdnjQ1EpC63VDKUAWY6uhNJs0v'
test:
  string: abc
  encryp: '{cipher}AIA5fE9B8tE4gUWx6wFWNvOt6E8Q3cP4hHjtDU3FvJsXiSL2zLIW8ZfGW3Qe0eVkXg1esu2N1NSd8t0G1//5/9dywAf9DnDUcSNJbHdMzj9CrfHAja171raywj0J98cDxjBXIWanFrX/6JQXz8H6mgxjo++/Scc14kt4MG/cB5QHsW1DlyBFigMZNmnkeIDqHTJepEKpJf3vh2TcngmbOzdq'
dubbo:
  scan: 
    annotationPackage: com.ccclubs.demo.api,com.ccclubs.frm.spring
  application:
    name: api
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    #port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false
  monitor:
    protocol: registry