server:
  port: 12001
spring:
  redis:
    host: 10.24.24.241
    database: 7
    pool:
      maxIdle: 8
      minIdle: 0
      maxActive: 64
      maxWait: -1
  data:
    mongodb:
      host: 10.24.24.241
      port: 3717
      username: dba_user
      password: office_97
      database: vc_history
      authenticationDatabase: vc_history
dubbo:
  scan:
    annotationPackage: com.ccclubs.gateway ,com.ccclubs.frm.mongodb,com.ccclubs.mongo,com.ccclubs.common
  application:
    name: gateway-808-srv-test
  registry:
    address: 10.122.72.180:2181,10.122.72.180:2182,10.122.72.180:2183
    protocol: zookeeper
    port: 20663
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20663
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false
#  monitor:
#    protocol: registry
#jt808网关转发到MQ的topic
mq:
  topic: ser
#jt808网关监听的端口
jt808Server:
  port: 26700
#socket最大空闲时间，单位秒
  maxOfflineTime: 720

#阿里云 MQ 配置
ons:
  producerId: PID_terminal_ser
  accessKey: M6dHCyKyKYUCNbW4
  secretKey: k6gOSH3dNJjFYze4CuxbBWS1PWqvVk

mqttAliyun:
  #阿里云 mqtt broker 地址
  host: tcp://mqtt.cn-hangzhou.aliyuncs.com
  #阿里云 mqtt broker 端口
  port: 1883
  #阿里云 mqClient ID 前缀
  preId: GID_pro
  #阿里云用户名
  userName: M6dHCyKyKYUCNbW4
  #阿里云密码
  pwd: 2u0w1llRPSxKeNSZDq95jQAE95c=
  #订阅主题
  subTopic: protocol/jt808/#
  #是否记录上行记录
  logUpDown: true

druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://10.132.27.108:3306/vc_data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: alpha_user
    password: 3CvQMOiJFihcVnOLOw6J
  initialSize: 2
  maxActive: 4
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: