tcp:
  port: 27700
boss:
  thread:
    count: 2
worker:
  thread:
    count: 4
#true: 连接复用；false：每次新建一个连接
so:
  keepalive: false
  backlog: 100

#kafka生产者配置
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#kafka Topic
kafka:
  topic:
    gateway:
      gb:
        error: topic_gb_error
        success-login: topic_gb_0x01
        success-real: topic_gb_0x02
        success-reissue: topic_gb_0x03
        success-logout: topic_gb_0x04
        success-heart: topic_gb_0x07
        success-time: topic_gb_0x08
        conn: topic_gb_online_status

pac:
  log:
    debug: true    #是否开启消息日志打印
  buffer:
    check: false    #是否打开buffer缓存检查（测试时开启）




