server:
  port: 12001

spring:
  redis:
    host: r-bp10b96658d427c4.redis.rds.aliyuncs.com
    password: zgjrB7aUk83plwCpyrEk
    database: 7
    pool:
      maxIdle: 8
      minIdle: 0
      maxActive: 64
      maxWait: -1
  data:
    mongodb:
      uri: mongodb://p2p_user:f5b4037f7d0791dc973#@dds-bp17a26e642a28741.mongodb.rds.aliyuncs.com:3717,dds-bp17a26e642a28742.mongodb.rds.aliyuncs.com:3717/ccclubs_p2p_data?replicaSet=mgset-2415881&maxPoolSize=50


dubbo:
  scan:
    annotationPackage: com.ccclubs.gateway ,com.ccclubs.frm.mongodb,com.ccclubs.mongodb,com.ccclubs.common
  application:
    name: gateway-808-srv
  registry:
    address: 10.47.97.150:2181,10.25.4.117:2182,10.24.24.188:2183
    protocol: zookeeper
    port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false
#  monitor:
#    protocol: registry
#jt808网关转发到MQ的topic
mq:
  topic: ser
#jt808网关监听的端口
jt808Server:
  port: 26700
#socket最大空闲时间，单位秒
  maxOfflineTime: 720

#阿里云 MQ 配置
ons:
  producerId: PID_terminal_ser
  accessKey: M6dHCyKyKYUCNbW4
  secretKey: k6gOSH3dNJjFYze4CuxbBWS1PWqvVk

mqttAliyun:
  #阿里云 mqtt broker 地址
  host: tcp://mqtt.cn-hangzhou.aliyuncs.com
  #阿里云 mqtt broker 端口
  port: 1883
  #阿里云 mqClient ID 前缀
  preId: GID_pro
  #阿里云用户名
  userName: M6dHCyKyKYUCNbW4
  #阿里云密码
  pwd: 2u0w1llRPSxKeNSZDq95jQAE95c=
  #订阅主题
  subTopic: protocol/jt808/#
  #是否记录上行记录
  logUpDown: true

druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://rm-bp1ly42351i7096mj.mysql.rds.aliyuncs.com:3306/ccclubs_data_center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: tmp_user
    password: RsyKWvf4U0bHSuzTfZTG
  initialSize: 2
  maxActive: 50
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: