server:
  port: 9000
spring:
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true

dubbo:
  scan:
    annotationPackage: com.ccclubs
  application:
    name: api
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    #port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  consumer:
    timeout: 120000
    check: false


druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://121.199.49.206:3306/ccclubs_data_center?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: zkj_user
    password: kANXZYqf2UzghVY7DnjP
  initialSize: 2
  maxActive: 4
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  scan:
    basePackage: com.ccclubs.**.mapper

spring:
 datasource:
   url: jdbc:mysql://121.199.49.206:3306/ccclubs_data_center?useUnicode=true&characterEncoding=utf8&autoReconnect=true
   username: zkj_user
   password: kANXZYqf2UzghVY7DnjP

jwt:
  header: Authorization
  secret: mySecret
  expiration: 1800
  route:
    authentication:
      path: auth
      refresh: refresh