phoenix:
  #zookeeper所在主机地址
  zk_url: hb-bp11zgdd317e4af0r-001.hbase.rds.aliyuncs.com,hb-bp11zgdd317e4af0r-006.hbase.rds.aliyuncs.com,hb-bp11zgdd317e4af0r-005.hbase.rds.aliyuncs.com

server:
  port: 12007

spring:
  redis:
    host: 127.0.0.1

dubbo:
  scan:
    annotationPackage: com.ccclubs.phoenix
  application:
    name: srv
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false
  monitor:
    protocol: registry
