server:
  port: 12007

dubbo:
  scan:
    annotationPackage: com.ccclubs.phoenix.api,com.ccclubs.frm.spring
  application:
    name: api
  registry:
    address: 118.25.77.128:2181
    protocol: zookeeper
    #port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  consumer:
    timeout: 120000
    check: false
  provider:
      timeout: 120000
      retries: -1

spring:
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true