server:
  port: 7005
spring:
  http: 
    encoding: 
      charset: UTF-8
      enable: true
      force: true

api:
  security:
      apiId: appKey
      appId: '{cipher}AIB6DsANDSW8Ehs0L8EcMJe7cjxfzwOP1+onlXhQryApv/JJod3syv1exOHUw/DEBaNdzkb1BqR01PdXs3+mKNxQUNtaY8xqztz3hiJx1S963Ke8pB5yOKwdJ0cDWO11k5Fi16QCCcB6Gxy3ASjLBPpK75iZwQx/paWhSkdCj7Tm7BjE+wnEEYtNTIB/YjXdnjQ1EpC63VDKUAWY6uhNJs0v'

dubbo:
  scan: 
    annotationPackage: com.ccclubs.quota.api,com.ccclubs.frm.spring
  application:
    name: api
  registry:
    address: 10.47.97.150:2181,10.25.4.117:2182,10.24.24.188:2183
    protocol: zookeeper
    #port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false

csIndexReport:
  templateReportPath: "/var/report/templateReportPath/excelTemplate.xls"
  conditionReportPath: "/var/report/conditionReportPath"
  generateReportPath: "/var/report/generateReportPath/zhong_tai_report.xls"
