server:
  port: 11115
  
spring:
  redis: 
    host: r-bp10b96658d427c4.redis.rds.aliyuncs.com
    password: zgjrB7aUk83plwCpyrEk
    database: 7
    pool:
      maxIdle: 8
      minIdle: 0
      maxActive: 64
      maxWait: -1
  data:  
    mongodb:  
     uri: mongodb://p2p_user:f5b4037f7d0791dc973#@dds-bp17a26e642a28741.mongodb.rds.aliyuncs.com:3717,dds-bp17a26e642a28742.mongodb.rds.aliyuncs.com:3717/ccclubs_p2p_data?replicaSet=mgset-2415881&maxPoolSize=50
      
dubbo:
  scan: 
    annotationPackage: com.ccclubs
  application:
    name: srv
  registry:
    address: 10.47.97.150:2181,10.25.4.117:2182,10.24.24.188:2183
    protocol: zookeeper
    port: 20660
  protocol:
    name: dubbo
    threads: 100
    port: 20660
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false
druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://rm-bp1ly42351i7096mj.mysql.rds.aliyuncs.com:3306/ccclubs_quota?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: quota_user
    password: jjN(HRXeh$HklmXkQW!IzAs
  initialSize: 2
  maxActive: 4
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: 
zt:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url:  jdbc:mysql://rm-bp1ly42351i7096mj.mysql.rds.aliyuncs.com:3306/ccclubs_data_center?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: quota_user
    password: jjN(HRXeh$HklmXkQW!IzAs
  updateInterval: 7
  avgDriveTimePerDay: 0.2,1.5,  1.3,2.5,  2.3,3.5,  3.3,6,  5.3,12