package com.ccclubs.olap.orm.mapper;

import com.ccclubs.olap.orm.model.CsHistoryState;
import com.ccclubs.olap.orm.model.CsHistoryStateExample;

import java.util.List;

/**
 * Created by Administrator on 2017/9/16 0016.
 */
public interface CsHistoryStateMapper {

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table cs_index_report
//     *
//     * @mbg.generated
//     */
//    int deleteByExample(CsHistoryStateExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table cs_index_report
//     *
//     * @mbg.generated
//     */
//    int insert(CsHistoryState record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table cs_index_report
//     *
//     * @mbg.generated
//     */
//    int insertSelective(CsHistoryStateExample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    List<CsHistoryState> selectByExample(CsHistoryStateExample example);

}
