package com.ccclubs.olap.orm.mapper;


import com.ccclubs.olap.orm.model.DriveMilesBasicZhifa;
import com.ccclubs.olap.orm.model.DriveMilesBasicZhifaExample;
import com.ccclubs.olap.orm.model.ZhiFABean;

import java.util.List;

/**
 * Created by Administrator on 2017/9/7 0007.
 */
public interface DriveMilesBasicZhifaMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    int deleteByExample(DriveMilesBasicZhifaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    int insert(DriveMilesBasicZhifa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    int insertSelective(DriveMilesBasicZhifaExample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    List<ZhiFABean> selectByExample(DriveMilesBasicZhifaExample example);

}
