package com.ccclubs.olap.orm.mapper;

import com.ccclubs.olap.orm.model.SocMilesBasicZhifa;
import com.ccclubs.olap.orm.model.SocMilesBasicZhifaExample;

import java.util.List;

/**
 * Created by Administrator on 2017/9/7 0007.
 */
public interface SocMilesBasicZhifaMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    int deleteByExample(SocMilesBasicZhifaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    int insert(SocMilesBasicZhifa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    int insertSelective(SocMilesBasicZhifa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    List<SocMilesBasicZhifa> selectByExample(SocMilesBasicZhifaExample example);



}
