package com.ccclubs.admin.controller.gb;

import com.ccclubs.admin.entity.VerFtpSerCrieria;
import com.ccclubs.admin.model.VerFtpSer;
import com.ccclubs.admin.query.VerFtpSerQuery;
import com.ccclubs.admin.service.IVerFtpSerService;
import com.ccclubs.admin.vo.TableResult;
import com.ccclubs.admin.vo.VoResult;
import com.github.pagehelper.PageInfo;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 升级文件服务器管理Controller
 * @category generated by NovaV1.0
 * 
 * @author 
 * @since V1.0
 */
@RestController
@RequestMapping("/version/ftpserver")
public class VerFtpSerController {

	@Autowired
	IVerFtpSerService verFtpSerService;

	/**
	 * 获取分页列表数据
	 * @param query
	 * @param page
	 * @param rows
	 * @return
	 */
	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public TableResult<VerFtpSer> list(VerFtpSerQuery query, @RequestParam(defaultValue = "0") Integer page,
                                       @RequestParam(defaultValue = "10") Integer rows) {
		PageInfo<VerFtpSer> pageInfo = verFtpSerService.getPage(query.getCrieria(), page, rows);
		List<VerFtpSer> list = pageInfo.getList();
		for(VerFtpSer data : list){
			registResolvers(data);
		}
		
		TableResult<VerFtpSer> r = new TableResult<>(pageInfo);
		return r;
	}

	/**
	 * 创建保存升级文件服务器管理
	 * @return
	 */
	@RequestMapping(value="/add", method = RequestMethod.POST)
	public VoResult<?> add(VerFtpSer data){
		verFtpSerService.insert(data);
		return VoResult.success();
	}
	
	/**
	 * 更新升级文件服务器管理
	 * @param data
	 * @return
	 */
	@RequestMapping(value="/update", method = RequestMethod.POST)
	public VoResult<?> update(VerFtpSer data){
		verFtpSerService.updateByPrimaryKeySelective(data);
		return VoResult.success();
	}
	
	/**
	 * 删除升级文件服务器管理
	 * @return
	 */
	@RequestMapping(value="delete", method = RequestMethod.DELETE)
	public VoResult<?> delete(@RequestParam(required=true)final Integer[] ids){
		verFtpSerService.batchDelete(ids);
		return VoResult.success();
	}
	
	/**
	 * 注册属性内容解析器
	 */
	void registResolvers(VerFtpSer data){
		if(data!=null){
			data.registResolver(com.ccclubs.admin.resolver.VerFtpSerResolver.服务器类型.getResolver());
		}
	}
	
	/**
	 * 获取单条升级文件服务器管理信息
	 */
	@RequestMapping(value="/detail/{id}", method = RequestMethod.GET)
	public VoResult<Map<String, VerFtpSer>> detail(@PathVariable(required = true) Integer id){
		VerFtpSer data = verFtpSerService.selectByPrimaryKey( id.intValue());
		Map<String, VerFtpSer> map = new HashMap<String, VerFtpSer>();
		registResolvers(data);
		map.put("tbody", data);
		return VoResult.success().setValue(map);
	}
	
	
	/**
	 * 根据文本检索升级文件服务器管理信息
	 */
	@RequestMapping(value="/query", method = RequestMethod.GET)
	public VoResult<Map<String, List<Map<String, Object>>>> query(String text , String where , VerFtpSer queryRecord){
		VerFtpSerCrieria query = new VerFtpSerCrieria();
		VerFtpSerCrieria.Criteria c = query.createCriteria();
		if(!StringUtils.isEmpty(text)){
			String val = String.valueOf(text);
			c.andnameLike(val);
		}
		if(!StringUtils.isEmpty(where)){
			Integer val = Integer.valueOf(where);
			c.andidEqualTo(val);
		}
		PageInfo<VerFtpSer> pageInfo = verFtpSerService.getPage(query, 0, 10);
		List<VerFtpSer> list = pageInfo.getList();

		List<Map<String, Object>> mapList = new ArrayList<Map<String,Object>>(list.size());
		Map<String, Object> map ;
		for (VerFtpSer data : list) {
			map = new HashMap<String, Object>();
			map.put("value", data.getid());
			map.put("text", data.getname());
			mapList.add(map);
		}
		return VoResult.success().setValue(mapList);
	}
	
}
