package com.ccclubs.admin.controller.gb;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.apache.commons.lang3.StringUtils;

import com.ccclubs.admin.vo.TableResult;

import com.ccclubs.admin.entity.VerUpgradeRecordCrieria;
import com.ccclubs.admin.model.VerUpgradeRecord;
import com.ccclubs.admin.service.IVerUpgradeRecordService;
import com.ccclubs.admin.query.VerUpgradeRecordQuery;
import com.ccclubs.admin.vo.VoResult;
import com.github.pagehelper.PageInfo;

/**
 * 车机升级记录Controller
 * @category generated by NovaV1.0
 * 
 * @author 
 * @since V1.0
 */
@RestController
@RequestMapping("/version/upgrade/record")
public class VerUpgradeRecordController {

	@Autowired
	IVerUpgradeRecordService verUpgradeRecordService;

	/**
	 * 获取分页列表数据
	 * @param query
	 * @param page
	 * @param rows
	 * @return
	 */
	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public TableResult<VerUpgradeRecord> list(VerUpgradeRecordQuery query, @RequestParam(defaultValue = "0") Integer page,
			@RequestParam(defaultValue = "10") Integer rows) {
		PageInfo<VerUpgradeRecord> pageInfo = verUpgradeRecordService.getPage(query.getCrieria(), page, rows);
		List<VerUpgradeRecord> list = pageInfo.getList();
		for(VerUpgradeRecord data : list){
			registResolvers(data);
		}
		
		TableResult<VerUpgradeRecord> r = new TableResult<>(pageInfo);
		return r;
	}

	/**
	 * 创建保存车机升级记录
	 * @return
	 */
	@RequestMapping(value="/add", method = RequestMethod.POST)
	public VoResult<?> add(VerUpgradeRecord data){
		verUpgradeRecordService.insert(data);
		return VoResult.success();
	}
	
	/**
	 * 更新车机升级记录
	 * @param data
	 * @return
	 */
	@RequestMapping(value="/update", method = RequestMethod.POST)
	public VoResult<?> update(VerUpgradeRecord data){
		verUpgradeRecordService.updateByPrimaryKeySelective(data);
		return VoResult.success();
	}
	
	/**
	 * 删除车机升级记录
	 * @return
	 */
	@RequestMapping(value="delete", method = RequestMethod.DELETE)
	public VoResult<?> delete(@RequestParam(required=true)final Integer[] ids){
		verUpgradeRecordService.batchDelete(ids);
		return VoResult.success();
	}
	
	/**
	 * 注册属性内容解析器
	 */
	void registResolvers(VerUpgradeRecord data){
		if(data!=null){
			data.registResolver(com.ccclubs.admin.resolver.VerUpgradeRecordResolver.车型.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.VerUpgradeRecordResolver.车机类型.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.VerUpgradeRecordResolver.当前版本.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.VerUpgradeRecordResolver.目的版本.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.VerUpgradeRecordResolver.状态.getResolver());
		}
	}
	
	/**
	 * 获取单条车机升级记录信息
	 */
	@RequestMapping(value="/detail/{id}", method = RequestMethod.GET)
	public VoResult<Map<String, VerUpgradeRecord>> detail(@PathVariable(required = true) Integer id){
		VerUpgradeRecord data = verUpgradeRecordService.selectByPrimaryKey( id.intValue());
		Map<String, VerUpgradeRecord> map = new HashMap<String, VerUpgradeRecord>();
		registResolvers(data);
		map.put("tbody", data);
		return VoResult.success().setValue(map);
	}
	
	
	/**
	 * 根据文本检索车机升级记录信息
	 */
	@RequestMapping(value="/query", method = RequestMethod.GET)
	public VoResult<Map<String, List<Map<String, Object>>>> query(String text , String where , VerUpgradeRecord queryRecord){
		VerUpgradeRecordCrieria query = new VerUpgradeRecordCrieria();
		VerUpgradeRecordCrieria.Criteria c = query.createCriteria();
		if(!StringUtils.isEmpty(text)){
			String val = String.valueOf(text);
			c.andvinLike(val);
		}
		if(!StringUtils.isEmpty(where)){
			Integer val = Integer.valueOf(where);
			c.andidEqualTo(val);
		}
		PageInfo<VerUpgradeRecord> pageInfo = verUpgradeRecordService.getPage(query, 0, 10);
		List<VerUpgradeRecord> list = pageInfo.getList();

		List<Map<String, Object>> mapList = new ArrayList<Map<String,Object>>(list.size());
		Map<String, Object> map ;
		for (VerUpgradeRecord data : list) {
			map = new HashMap<String, Object>();
			map.put("value", data.getid());
			map.put("text", data.getvin());
			mapList.add(map);
		}
		return VoResult.success().setValue(mapList);
	}
	
}
