package com.ccclubs.admin.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.apache.commons.lang3.StringUtils;

import com.ccclubs.admin.vo.TableResult;

import com.ccclubs.admin.entity.CsCanCrieria;
import com.ccclubs.admin.model.CsCan;
import com.ccclubs.admin.service.ICsCanService;
import com.ccclubs.admin.query.CsCanQuery;
import com.ccclubs.admin.vo.VoResult;
import com.github.pagehelper.PageInfo;

/**
 * 车辆实时CAN信息Controller
 * @category generated by NovaV1.0
 * 
 * @author 
 * @since V1.0
 */
@RestController
@RequestMapping("/monitor/can")
public class CsCanController {

	@Autowired
	ICsCanService csCanService;

	/**
	 * 获取分页列表数据
	 * @param query
	 * @param page
	 * @param rows
	 * @return
	 */
	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public TableResult<CsCan> list(CsCanQuery query, @RequestParam(defaultValue = "0") Integer page,
			@RequestParam(defaultValue = "10") Integer rows) {
		PageInfo<CsCan> pageInfo = csCanService.getPage(query.getCrieria(), page, rows);
		List<CsCan> list = pageInfo.getList();
		for(CsCan data : list){
			registResolvers(data);
		}
		
		TableResult<CsCan> r = new TableResult<>(pageInfo);
		return r;
	}

	
	
	
	/**
	 * 注册属性内容解析器
	 */
	void registResolvers(CsCan data){
		if(data!=null){
			data.registResolver(com.ccclubs.admin.resolver.CsCanResolver.接入商.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.CsCanResolver.车机号.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.CsCanResolver.车辆.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.CsCanResolver.CAN类型.getResolver());
		}
	}
	
	/**
	 * 获取单条车辆实时CAN信息信息
	 */
	@RequestMapping(value="/detail/{id}", method = RequestMethod.GET)
	public VoResult<Map<String, CsCan>> detail(@PathVariable(required = true) Long id){
		CsCan data = csCanService.selectByPrimaryKey( id.intValue());
		Map<String, CsCan> map = new HashMap<String, CsCan>();
		registResolvers(data);
		map.put("tbody", data);
		return VoResult.success().setValue(map);
	}
	
	
	/**
	 * 根据文本检索车辆实时CAN信息信息
	 */
	@RequestMapping(value="/query", method = RequestMethod.GET)
	public VoResult<Map<String, List<Map<String, Object>>>> query(String text , String where , CsCan queryRecord){
		CsCanCrieria query = new CsCanCrieria();
		CsCanCrieria.Criteria c = query.createCriteria();
		if(!StringUtils.isEmpty(text)){
			String val = String.valueOf(text);
			c.andcscNumberEqualTo(val);
		}
		if(!StringUtils.isEmpty(where)){
			Long val = Long.valueOf(where);
			c.andcscIdEqualTo(val);
		}
		PageInfo<CsCan> pageInfo = csCanService.getPage(query, 0, 10);
		List<CsCan> list = pageInfo.getList();

		List<Map<String, Object>> mapList = new ArrayList<Map<String,Object>>(list.size());
		Map<String, Object> map ;
		for (CsCan data : list) {
			map = new HashMap<String, Object>();
			map.put("value", data.getCscId());
			map.put("text", data.getCscNumber());
			mapList.add(map);
		}
		return VoResult.success().setValue(mapList);
	}
	
}
