package com.ccclubs.admin.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.apache.commons.lang3.StringUtils;

import com.ccclubs.admin.vo.TableResult;

import com.ccclubs.admin.entity.CsVehicleCrieria;
import com.ccclubs.admin.model.CsVehicle;
import com.ccclubs.admin.service.ICsVehicleService;
import com.ccclubs.admin.query.CsVehicleQuery;
import com.ccclubs.admin.vo.VoResult;
import com.github.pagehelper.PageInfo;

/**
 * 车辆信息管理Controller
 * @category generated by NovaV1.0
 * 
 * @author 
 * @since V1.0
 */
@RestController
@RequestMapping("/admin/vehicle")
public class CsVehicleController {

	@Autowired
	ICsVehicleService csVehicleService;

	/**
	 * 获取分页列表数据
	 * @param query
	 * @param page
	 * @param rows
	 * @return
	 */
	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public TableResult<CsVehicle> list(CsVehicleQuery query, @RequestParam(defaultValue = "0") Integer page,
			@RequestParam(defaultValue = "10") Integer rows) {
		PageInfo<CsVehicle> pageInfo = csVehicleService.getPage(query.getCrieria(), page, rows);
		List<CsVehicle> list = pageInfo.getList();
		for(CsVehicle data : list){
			registResolvers(data);
		}
		
		TableResult<CsVehicle> r = new TableResult<>(pageInfo);
		return r;
	}

	/**
	 * 创建保存车辆信息管理
	 * @return
	 */
	@RequestMapping(value="/add", method = RequestMethod.POST)
	public VoResult<?> add(CsVehicle data){
		csVehicleService.insert(data);
		return VoResult.success();
	}
	
	/**
	 * 更新车辆信息管理
	 * @param data
	 * @return
	 */
	@RequestMapping(value="/update", method = RequestMethod.POST)
	public VoResult<?> update(CsVehicle data){
		csVehicleService.updateByPrimaryKeySelective(data);
		return VoResult.success();
	}
	
	/**
	 * 删除车辆信息管理
	 * @return
	 */
	@RequestMapping(value="delete", method = RequestMethod.DELETE)
	public VoResult<?> delete(@RequestParam(required=true)final Long[] ids){
		csVehicleService.batchDelete(ids);
		return VoResult.success();
	}
	
	/**
	 * 注册属性内容解析器
	 */
	void registResolvers(CsVehicle data){
		if(data!=null){
			data.registResolver(com.ccclubs.admin.resolver.CsVehicleResolver.接入商.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.CsVehicleResolver.车型.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.CsVehicleResolver.车机设备.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.CsVehicleResolver.颜色.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.CsVehicleResolver.地标类型.getResolver());
			data.registResolver(com.ccclubs.admin.resolver.CsVehicleResolver.状态.getResolver());
		}
	}
	
	/**
	 * 获取单条车辆信息管理信息
	 */
	@RequestMapping(value="/detail/{id}", method = RequestMethod.GET)
	public VoResult<Map<String, CsVehicle>> detail(@PathVariable(required = true) Long id){
		CsVehicle data = csVehicleService.selectByPrimaryKey( id.intValue());
		Map<String, CsVehicle> map = new HashMap<String, CsVehicle>();
		registResolvers(data);
		map.put("tbody", data);
		return VoResult.success().setValue(map);
	}
	
	/**
	 * 更换TBox
	 * @return
	 */
	@RequestMapping(value="/bind", method = RequestMethod.POST)
	public VoResult<?> bind(CsVehicle data){
		csVehicleService.updateByPrimaryKeySelective(data);
		return VoResult.success();
	}
	
	/**
	 * 根据文本检索车辆信息管理信息
	 */
	@RequestMapping(value="/query", method = RequestMethod.GET)
	public VoResult<Map<String, List<Map<String, Object>>>> query(String text , String where , CsVehicle queryRecord){
		CsVehicleCrieria query = new CsVehicleCrieria();
		CsVehicleCrieria.Criteria c = query.createCriteria();
		if(!StringUtils.isEmpty(text)){
			String val = String.valueOf(text);
			c.andcsvVinLike(val);
		}
		if(!StringUtils.isEmpty(where)){
			Integer val = Integer.valueOf(where);
			c.andcsvIdEqualTo(val);
		}
		PageInfo<CsVehicle> pageInfo = csVehicleService.getPage(query, 0, 10);
		List<CsVehicle> list = pageInfo.getList();

		List<Map<String, Object>> mapList = new ArrayList<Map<String,Object>>(list.size());
		Map<String, Object> map ;
		for (CsVehicle data : list) {
			map = new HashMap<String, Object>();
			map.put("value", data.getCsvId());
			map.put("text", data.getCsvVin());
			mapList.add(map);
		}
		return VoResult.success().setValue(mapList);
	}
	
}
