package com.ccclubs.admin.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ccclubs.admin.resolver.HistoryStateResolver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.apache.commons.lang3.StringUtils;

import com.ccclubs.admin.vo.TableResult;

import com.ccclubs.admin.model.HistoryState;
import com.ccclubs.admin.service.IHistoryStateService;
import com.ccclubs.admin.query.HistoryStateQuery;
import com.ccclubs.admin.vo.VoResult;
import com.github.pagehelper.PageInfo;

/**
 * 车辆状态历史数据Controller
 * @category generated by NovaV1.0
 * 
 * @author 
 * @since V1.0
 */
@RestController
@RequestMapping("/monitor/historyState")
public class HistoryStateController {

	@Autowired
	IHistoryStateService historyStateService;

	/**
	 * 获取分页列表数据
	 * @param query
	 * @param page
	 * @param rows
	 * @return
	 */
	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public TableResult<HistoryState> list(HistoryStateQuery query, @RequestParam(defaultValue = "0") Integer page,
			@RequestParam(defaultValue = "10") Integer rows,@RequestParam(defaultValue = "desc" )String order ) {
		TableResult<HistoryState> pageInfo = historyStateService.getPage(query, page, rows,order);
		List<HistoryState> list = pageInfo.getData();
		for(HistoryState data : list){
			registResolvers(data);
		}
		return pageInfo;
	}

	
	
	
	/**
	 * 注册属性内容解析器
	 */
	void registResolvers(HistoryState data){
		if(data!=null){
			data.registResolver(HistoryStateResolver.下位机时间.getResolver());
			data.registResolver(HistoryStateResolver.添加时间.getResolver());
			data.registResolver(HistoryStateResolver.充电状态.getResolver());
			data.registResolver(HistoryStateResolver.gps有效性.getResolver());
			data.registResolver(HistoryStateResolver.循环模式.getResolver());
			data.registResolver(HistoryStateResolver.PTC启停.getResolver());
			data.registResolver(HistoryStateResolver.压缩机状态.getResolver());
			data.registResolver(HistoryStateResolver.档风量.getResolver());
			data.registResolver(HistoryStateResolver.省电模式.getResolver());
			data.registResolver(HistoryStateResolver.发动机.getResolver());
			data.registResolver(HistoryStateResolver.网络类型.getResolver());
			data.registResolver(HistoryStateResolver.档位.getResolver());
		}
	}
	
	/**
	 * 获取单条车辆状态历史数据信息
	 */
	/*@RequestMapping(value="/detail/{id}", method = RequestMethod.GET)
	public VoResult<Map<String, HistoryState>> detail(@PathVariable(required = true) Long id){
		HistoryState data = historyStateService.selectByPrimaryKey( id.intValue());
		Map<String, HistoryState> map = new HashMap<String, HistoryState>();
		registResolvers(data);
		map.put("tbody", data);
		return VoResult.success().setValue(map);
	}
	*/
	
	/**
	 * 根据文本检索车辆状态历史数据信息
	 */
	/*@RequestMapping(value="/query", method = RequestMethod.GET)
	public VoResult<Map<String, List<Map<String, Object>>>> query(String text , String where , HistoryState queryRecord){
		HistoryStateCrieria query = new HistoryStateCrieria();
		HistoryStateCrieria.Criteria c = query.createCriteria();
		if(!StringUtils.isEmpty(text)){
			Long val = Long.valueOf(text);
			c.andcarStateHistoryIdEqualTo(val);
		}
		if(!StringUtils.isEmpty(where)){
			Long val = Long.valueOf(where);
			c.andcarStateHistoryIdEqualTo(val);
		}
		PageInfo<HistoryState> pageInfo = historyStateService.getPage(query, 0, 10);
		List<HistoryState> list = pageInfo.getList();

		List<Map<String, Object>> mapList = new ArrayList<Map<String,Object>>(list.size());
		Map<String, Object> map ;
		for (HistoryState data : list) {
			map = new HashMap<String, Object>();
			map.put("value", data.getCarStateHistoryId());
			map.put("text", data.getCarStateHistoryId());
			mapList.add(map);
		}
		return VoResult.success().setValue(mapList);
	}*/
	
}
