package com.ccclubs.admin.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.apache.commons.lang3.StringUtils;

import com.ccclubs.admin.vo.TableResult;

import com.ccclubs.admin.model.HistoryCan;
import com.ccclubs.admin.service.IHistoryCanService;
import com.ccclubs.admin.query.HistoryCanQuery;
import com.ccclubs.admin.vo.VoResult;
import com.github.pagehelper.PageInfo;

/**
 * 车辆CAN历史数据Controller
 * @category generated by NovaV1.0
 * 
 * @author 
 * @since V1.0
 */
@RestController
@RequestMapping("/monitor/historyCan")
public class HistoryCanController {

	@Autowired
	IHistoryCanService historyCanService;

	/**
	 * 获取分页列表数据
	 * @param query
	 * @param page
	 * @param rows
	 * @return
	 */
	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public TableResult<HistoryCan> list(HistoryCanQuery query, @RequestParam(defaultValue = "0") Integer page,
										@RequestParam(defaultValue = "10") Integer rows,
										@RequestParam(defaultValue = "desc" )String order,
										@RequestParam(defaultValue = "true" )Boolean isResolve) {
		if (null==query.getCsNumberEquals()){return  new TableResult<HistoryCan>();}
		TableResult<HistoryCan> pageInfo = historyCanService.getPage(query, page, rows,order);
		List<HistoryCan> list = pageInfo.getData();
		for(HistoryCan data : list){
			registResolvers(data);
		}
		return pageInfo;
	}

	
	
	
	/**
	 * 注册属性内容解析器
	 */
	void registResolvers(HistoryCan data){
		if(data!=null){
		}
	}

}
