package com.ccclubs.quota.orm.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Created by Administrator on 2018/1/3 0003.
 */
public class CsMiddleReportExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected List<CsMiddleReportExample.Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public CsMiddleReportExample() {
        oredCriteria = new ArrayList<CsMiddleReportExample.Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public List<CsMiddleReportExample.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public void or(CsMiddleReportExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public CsMiddleReportExample.Criteria or() {
        CsMiddleReportExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public CsMiddleReportExample.Criteria createCriteria() {
        CsMiddleReportExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected CsMiddleReportExample.Criteria createCriteriaInternal() {
        CsMiddleReportExample.Criteria criteria = new CsMiddleReportExample.Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<CsMiddleReportExample.Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<CsMiddleReportExample.Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<CsMiddleReportExample.Criterion> getAllCriteria() {
            return criteria;
        }

        public List<CsMiddleReportExample.Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new CsMiddleReportExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new CsMiddleReportExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new CsMiddleReportExample.Criterion(condition, value1, value2));
        }




        public CsMiddleReportExample.Criteria andCsmrIdIsNull() {
            addCriterion("csmr_id is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdIsNotNull() {
            addCriterion("csmr_id is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdEqualTo(Long value) {
            addCriterion("csmr_id =", value, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdNotEqualTo(Long value) {
            addCriterion("csmr_id <>", value, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdGreaterThan(Long value) {
            addCriterion("csmr_id >", value, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("csmr_id >=", value, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdLessThan(Long value) {
            addCriterion("csmr_id <", value, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdLessThanOrEqualTo(Long value) {
            addCriterion("csmr_id <=", value, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdLike(Long value) {
            addCriterion("csmr_id like", value, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdNotLike(Long value) {
            addCriterion("csmr_id not like", value, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdIn(List<Long> values) {
            addCriterion("csmr_id in", values, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdNotIn(List<Long> values) {
            addCriterion("csmr_id not in", values, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdBetween(Long value1, Long value2) {
            addCriterion("csmr_id between", value1, value2, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrIdNotBetween(Long value1, Long value2) {
            addCriterion("csmr_id not between", value1, value2, "csmrId");
            return (CsMiddleReportExample.Criteria) this;
        }

















        public CsMiddleReportExample.Criteria andCsmrVinIsNull() {
            addCriterion("csmr_vin is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinIsNotNull() {
            addCriterion("csmr_vin is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinEqualTo(String value) {
            addCriterion("csmr_vin =", value, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinNotEqualTo(String value) {
            addCriterion("csmr_vin <>", value, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinGreaterThan(String value) {
            addCriterion("csmr_vin >", value, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinGreaterThanOrEqualTo(String value) {
            addCriterion("csmr_vin >=", value, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinLessThan(String value) {
            addCriterion("csmr_vin <", value, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinLessThanOrEqualTo(String value) {
            addCriterion("csmr_vin <=", value, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinLike(String value) {
            addCriterion("csmr_vin like", value, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinNotLike(String value) {
            addCriterion("csmr_vin not like", value, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinIn(List<String> values) {
            addCriterion("csmr_vin in", values, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinNotIn(List<String> values) {
            addCriterion("csmr_vin not in", values, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinBetween(String value1, String value2) {
            addCriterion("csmr_vin between", value1, value2, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrVinNotBetween(String value1, String value2) {
            addCriterion("csmr_vin not between", value1, value2, "csmrVin");
            return (CsMiddleReportExample.Criteria) this;
        }





        public CsMiddleReportExample.Criteria andCsmrNumberIsNull() {
            addCriterion("csmr_number is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberIsNotNull() {
            addCriterion("csmr_number is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberEqualTo(String value) {
            addCriterion("csmr_number =", value, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberNotEqualTo(String value) {
            addCriterion("csmr_number <>", value, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberGreaterThan(String value) {
            addCriterion("csmr_number >", value, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberGreaterThanOrEqualTo(String value) {
            addCriterion("csmr_number >=", value, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberLessThan(String value) {
            addCriterion("csmr_number <", value, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberLessThanOrEqualTo(String value) {
            addCriterion("csmr_number <=", value, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberLike(String value) {
            addCriterion("csmr_number like", value, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberNotLike(String value) {
            addCriterion("csmr_number not like", value, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberIn(List<String> values) {
            addCriterion("csmr_number in", values, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberNotIn(List<String> values) {
            addCriterion("csmr_number not in", values, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberBetween(String value1, String value2) {
            addCriterion("csmr_number between", value1, value2, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrNumberNotBetween(String value1, String value2) {
            addCriterion("csmr_number not between", value1, value2, "csmrNumber");
            return (CsMiddleReportExample.Criteria) this;
        }



        public CsMiddleReportExample.Criteria andCsmrCarNoIsNull() {
            addCriterion("csmr_car_no is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoIsNotNull() {
            addCriterion("csmr_car_no is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoEqualTo(String value) {
            addCriterion("csmr_car_no =", value, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoNotEqualTo(String value) {
            addCriterion("csmr_car_no <>", value, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoGreaterThan(String value) {
            addCriterion("csmr_car_no >", value, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoGreaterThanOrEqualTo(String value) {
            addCriterion("csmr_car_no >=", value, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoLessThan(String value) {
            addCriterion("csmr_car_no <", value, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoLessThanOrEqualTo(String value) {
            addCriterion("csmr_car_no <=", value, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoIn(List<String> values) {
            addCriterion("csmr_car_no in", values, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoNotIn(List<String> values) {
            addCriterion("csmr_car_no not in", values, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoBetween(String value1, String value2) {
            addCriterion("csmr_car_no between", value1, value2, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrCarNoNotBetween(String value1, String value2) {
            addCriterion("csmr_car_no not between", value1, value2, "csmrCarNo");
            return (CsMiddleReportExample.Criteria) this;
        }


        
        public CsMiddleReportExample.Criteria andCsmrModelIsNull() {
            addCriterion("csmr_model is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelIsNotNull() {
            addCriterion("csmr_model is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelEqualTo(Integer value) {
            addCriterion("csmr_model =", value, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelNotEqualTo(Integer value) {
            addCriterion("csmr_model <>", value, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelGreaterThan(Integer value) {
            addCriterion("csmr_model >", value, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelGreaterThanOrEqualTo(Integer value) {
            addCriterion("csmr_model >=", value, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelLessThan(Integer value) {
            addCriterion("csmr_model <", value, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelLessThanOrEqualTo(Integer value) {
            addCriterion("csmr_model <=", value, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelIn(List<Integer> values) {
            addCriterion("csmr_model in", values, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelNotIn(List<Integer> values) {
            addCriterion("csmr_model not in", values, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelBetween(Integer value1, Integer value2) {
            addCriterion("csmr_model between", value1, value2, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrModelNotBetween(Integer value1, Integer value2) {
            addCriterion("csmr_model not between", value1, value2, "csmrModel");
            return (CsMiddleReportExample.Criteria) this;
        }



        public CsMiddleReportExample.Criteria andCsmrObdMileIsNull() {
            addCriterion("csmr_obd_mile is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileIsNotNull() {
            addCriterion("csmr_obd_mile is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileEqualTo(BigDecimal value) {
            addCriterion("csmr_obd_mile =", value, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileNotEqualTo(BigDecimal value) {
            addCriterion("csmr_obd_mile <>", value, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileGreaterThan(BigDecimal value) {
            addCriterion("csmr_obd_mile >", value, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("csmr_obd_mile >=", value, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileLessThan(BigDecimal value) {
            addCriterion("csmr_obd_mile <", value, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileLessThanOrEqualTo(BigDecimal value) {
            addCriterion("csmr_obd_mile <=", value, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileIn(List<BigDecimal> values) {
            addCriterion("csmr_obd_mile in", values, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileNotIn(List<BigDecimal> values) {
            addCriterion("csmr_obd_mile not in", values, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("csmr_obd_mile between", value1, value2, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrObdMileNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("csmr_obd_mile not between", value1, value2, "csmrObdMile");
            return (CsMiddleReportExample.Criteria) this;
        }


        public CsMiddleReportExample.Criteria andCsmrExceptionMileIsNull() {
            addCriterion("csmr_exception_mile is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileIsNotNull() {
            addCriterion("csmr_exception_mile is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileEqualTo(BigDecimal value) {
            addCriterion("csmr_exception_mile =", value, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileNotEqualTo(BigDecimal value) {
            addCriterion("csmr_exception_mile <>", value, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileGreaterThan(BigDecimal value) {
            addCriterion("csmr_exception_mile >", value, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("csmr_exception_mile >=", value, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileLessThan(BigDecimal value) {
            addCriterion("csmr_exception_mile <", value, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileLessThanOrEqualTo(BigDecimal value) {
            addCriterion("csmr_exception_mile <=", value, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileIn(List<BigDecimal> values) {
            addCriterion("csmr_exception_mile in", values, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileNotIn(List<BigDecimal> values) {
            addCriterion("csmr_exception_mile not in", values, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("csmr_exception_mile between", value1, value2, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrExceptionMileNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("csmr_exception_mile not between", value1, value2, "csmrExceptionMile");
            return (CsMiddleReportExample.Criteria) this;
        }


        //
        public CsMiddleReportExample.Criteria andCsmrMileStateIsNull() {
            addCriterion("csmr_mile_state is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateIsNotNull() {
            addCriterion("csmr_mile_state is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateEqualTo(Short value) {
            addCriterion("csmr_mile_state =", value, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateNotEqualTo(Short value) {
            addCriterion("csmr_mile_state <>", value, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateGreaterThan(Short value) {
            addCriterion("csmr_mile_state >", value, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateGreaterThanOrEqualTo(Short value) {
            addCriterion("csmr_mile_state >=", value, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateLessThan(Short value) {
            addCriterion("csmr_mile_state <", value, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateLessThanOrEqualTo(Short value) {
            addCriterion("csmr_mile_state <=", value, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateIn(List<Short> values) {
            addCriterion("csmr_mile_state in", values, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateNotIn(List<Short> values) {
            addCriterion("csmr_mile_state not in", values, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateBetween(Short value1, Short value2) {
            addCriterion("csmr_mile_state between", value1, value2, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrMileStateNotBetween(Short value1, Short value2) {
            addCriterion("csmr_mile_state not between", value1, value2, "csmrMileState");
            return (CsMiddleReportExample.Criteria) this;
        }



        //
        public CsMiddleReportExample.Criteria andCsmrStatusIsNull() {
            addCriterion("csmr_status is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusIsNotNull() {
            addCriterion("csmr_status is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusEqualTo(Short value) {
            addCriterion("csmr_status =", value, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusNotEqualTo(Short value) {
            addCriterion("csmr_status <>", value, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusGreaterThan(Short value) {
            addCriterion("csmr_status >", value, "CsmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("csmr_status >=", value, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusLessThan(Short value) {
            addCriterion("csmr_status <", value, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusLessThanOrEqualTo(Short value) {
            addCriterion("csmr_status <=", value, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusIn(List<Short> values) {
            addCriterion("csmr_status in", values, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusNotIn(List<Short> values) {
            addCriterion("csmr_status not in", values, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusBetween(Short value1, Short value2) {
            addCriterion("csmr_status between", value1, value2, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrStatusNotBetween(Short value1, Short value2) {
            addCriterion("csmr_status not between", value1, value2, "csmrStatus");
            return (CsMiddleReportExample.Criteria) this;
        }

        //
        public CsMiddleReportExample.Criteria andCsmrDomainIsNull() {
            addCriterion("csmr_domain is null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainIsNotNull() {
            addCriterion("csmr_domain is not null");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainEqualTo(Short value) {
            addCriterion("csmr_domain =", value, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainNotEqualTo(Short value) {
            addCriterion("csmr_domain <>", value, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainGreaterThan(Short value) {
            addCriterion("csmr_domain >", value, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainGreaterThanOrEqualTo(Short value) {
            addCriterion("csmr_domain >=", value, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainLessThan(Short value) {
            addCriterion("csmr_domain <", value, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainLessThanOrEqualTo(Short value) {
            addCriterion("csmr_domain <=", value, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainIn(List<Short> values) {
            addCriterion("csmr_domain in", values, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainNotIn(List<Short> values) {
            addCriterion("csmr_domain not in", values, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainBetween(Short value1, Short value2) {
            addCriterion("csmr_domain between", value1, value2, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }

        public CsMiddleReportExample.Criteria andCsmrDomainNotBetween(Short value1, Short value2) {
            addCriterion("csmr_domain not between", value1, value2, "csmrDomain");
            return (CsMiddleReportExample.Criteria) this;
        }


        //
        public Criteria andCsmrAddTimeIsNull() {
            addCriterion("csmr_add_time is null");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeIsNotNull() {
            addCriterion("csmr_add_time is not null");
            return (Criteria) this;
        }


        public Criteria andCsmrAddTimeEqualTo(Date value) {
            addCriterion("csmr_add_time =", value, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeNotEqualTo(Date value) {
            addCriterion("csmr_add_time <>", value, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeGreaterThan(Date value) {
            addCriterion("csmr_add_time >", value, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("csmr_add_time >=", value, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeLessThan(Date value) {
            addCriterion("csmr_add_time <", value, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("csmr_add_time <=", value, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeIn(List<Date> values) {
            addCriterion("csmr_add_time in", values, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeNotIn(List<Date> values) {
            addCriterion("csmr_add_time not in", values, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeBetween(Date value1, Date value2) {
            addCriterion("csmr_add_time between", value1, value2, "csmrAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmrAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("csmr_add_time not between", value1, value2, "csmrAddTime");
            return (Criteria) this;
        }

        //

        public Criteria andCsmrProdTimeIsNull() {
            addCriterion("csmr_prod_time is null");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeIsNotNull() {
            addCriterion("csmr_prod_time is not null");
            return (Criteria) this;
        }


        public Criteria andCsmrProdTimeEqualTo(Date value) {
            addCriterion("csmr_prod_time =", value, "csmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeNotEqualTo(Date value) {
            addCriterion("csmr_prod_time <>", value, "csmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeGreaterThan(Date value) {
            addCriterion("csmr_prod_time >", value, "csmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("csmr_prod_time >=", value, "CsmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeLessThan(Date value) {
            addCriterion("csmr_prod_time <", value, "csmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeLessThanOrEqualTo(Date value) {
            addCriterion("csmr_prod_time <=", value, "csmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeIn(List<Date> values) {
            addCriterion("csmr_prod_time in", values, "CsmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeNotIn(List<Date> values) {
            addCriterion("csmr_prod_time not in", values, "csmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeBetween(Date value1, Date value2) {
            addCriterion("csmr_prod_time between", value1, value2, "csmrProdTime");
            return (Criteria) this;
        }

        public Criteria andCsmrProdTimeNotBetween(Date value1, Date value2) {
            addCriterion("csmr_prod_time not between", value1, value2, "csmrProdTime");
            return (Criteria) this;
        }

        //

        public Criteria andCsmrSaleTimeIsNull() {
            addCriterion("csmr_sale_time is null");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeIsNotNull() {
            addCriterion("csmr_sale_time is not null");
            return (Criteria) this;
        }


        public Criteria andCsmrSaleTimeEqualTo(Date value) {
            addCriterion("csmr_sale_time =", value, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeNotEqualTo(Date value) {
            addCriterion("csmr_sale_time <>", value, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeGreaterThan(Date value) {
            addCriterion("csmr_sale_time >", value, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("csmr_sale_time >=", value, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeLessThan(Date value) {
            addCriterion("csmr_sale_time <", value, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeLessThanOrEqualTo(Date value) {
            addCriterion("csmr_sale_time <=", value, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeIn(List<Date> values) {
            addCriterion("csmr_sale_time in", values, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeNotIn(List<Date> values) {
            addCriterion("csmr_sale_time not in", values, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeBetween(Date value1, Date value2) {
            addCriterion("csmr_sale_time between", value1, value2, "csmrSaleTime");
            return (Criteria) this;
        }

        public Criteria andCsmrSaleTimeNotBetween(Date value1, Date value2) {
            addCriterion("csmr_sale_time not between", value1, value2, "csmrSaleTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_index_report
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends CsMiddleReportExample.GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
