package com.ccclubs.manage.orm.model;

import java.io.Serializable;
import java.util.Date;

public class CsStatistics implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_id
     *
     * @mbg.generated
     */
    private Integer cssId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_time
     *
     * @mbg.generated
     */
    private Date cssTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_unit_time
     *
     * @mbg.generated
     */
    private Long cssUnitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_registered_num
     *
     * @mbg.generated
     */
    private Integer cssRegisteredNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_online_num
     *
     * @mbg.generated
     */
    private Integer cssOnlineNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_offline_num
     *
     * @mbg.generated
     */
    private Integer cssOfflineNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_run_num
     *
     * @mbg.generated
     */
    private Integer cssRunNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_charging_num
     *
     * @mbg.generated
     */
    private Integer cssChargingNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_total_mileage
     *
     * @mbg.generated
     */
    private Float cssTotalMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_total_charge
     *
     * @mbg.generated
     */
    private Float cssTotalCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_total_power_consumption
     *
     * @mbg.generated
     */
    private Float cssTotalPowerConsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_total_run_time
     *
     * @mbg.generated
     */
    private Long cssTotalRunTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_increment_mileage
     *
     * @mbg.generated
     */
    private Long cssIncrementMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_access
     *
     * @mbg.generated
     */
    private Integer cssAccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_statistics.css_car_model
     *
     * @mbg.generated
     */
    private Integer cssCarModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_id
     *
     * @return the value of cs_statistics.css_id
     *
     * @mbg.generated
     */
    public Integer getCssId() {
        return cssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_id
     *
     * @param cssId the value for cs_statistics.css_id
     *
     * @mbg.generated
     */
    public void setCssId(Integer cssId) {
        this.cssId = cssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_time
     *
     * @return the value of cs_statistics.css_time
     *
     * @mbg.generated
     */
    public Date getCssTime() {
        return cssTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_time
     *
     * @param cssTime the value for cs_statistics.css_time
     *
     * @mbg.generated
     */
    public void setCssTime(Date cssTime) {
        this.cssTime = cssTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_unit_time
     *
     * @return the value of cs_statistics.css_unit_time
     *
     * @mbg.generated
     */
    public Long getCssUnitTime() {
        return cssUnitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_unit_time
     *
     * @param cssUnitTime the value for cs_statistics.css_unit_time
     *
     * @mbg.generated
     */
    public void setCssUnitTime(Long cssUnitTime) {
        this.cssUnitTime = cssUnitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_registered_num
     *
     * @return the value of cs_statistics.css_registered_num
     *
     * @mbg.generated
     */
    public Integer getCssRegisteredNum() {
        return cssRegisteredNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_registered_num
     *
     * @param cssRegisteredNum the value for cs_statistics.css_registered_num
     *
     * @mbg.generated
     */
    public void setCssRegisteredNum(Integer cssRegisteredNum) {
        this.cssRegisteredNum = cssRegisteredNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_online_num
     *
     * @return the value of cs_statistics.css_online_num
     *
     * @mbg.generated
     */
    public Integer getCssOnlineNum() {
        return cssOnlineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_online_num
     *
     * @param cssOnlineNum the value for cs_statistics.css_online_num
     *
     * @mbg.generated
     */
    public void setCssOnlineNum(Integer cssOnlineNum) {
        this.cssOnlineNum = cssOnlineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_offline_num
     *
     * @return the value of cs_statistics.css_offline_num
     *
     * @mbg.generated
     */
    public Integer getCssOfflineNum() {
        return cssOfflineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_offline_num
     *
     * @param cssOfflineNum the value for cs_statistics.css_offline_num
     *
     * @mbg.generated
     */
    public void setCssOfflineNum(Integer cssOfflineNum) {
        this.cssOfflineNum = cssOfflineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_run_num
     *
     * @return the value of cs_statistics.css_run_num
     *
     * @mbg.generated
     */
    public Integer getCssRunNum() {
        return cssRunNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_run_num
     *
     * @param cssRunNum the value for cs_statistics.css_run_num
     *
     * @mbg.generated
     */
    public void setCssRunNum(Integer cssRunNum) {
        this.cssRunNum = cssRunNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_charging_num
     *
     * @return the value of cs_statistics.css_charging_num
     *
     * @mbg.generated
     */
    public Integer getCssChargingNum() {
        return cssChargingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_charging_num
     *
     * @param cssChargingNum the value for cs_statistics.css_charging_num
     *
     * @mbg.generated
     */
    public void setCssChargingNum(Integer cssChargingNum) {
        this.cssChargingNum = cssChargingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_total_mileage
     *
     * @return the value of cs_statistics.css_total_mileage
     *
     * @mbg.generated
     */
    public Float getCssTotalMileage() {
        return cssTotalMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_total_mileage
     *
     * @param cssTotalMileage the value for cs_statistics.css_total_mileage
     *
     * @mbg.generated
     */
    public void setCssTotalMileage(Float cssTotalMileage) {
        this.cssTotalMileage = cssTotalMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_total_charge
     *
     * @return the value of cs_statistics.css_total_charge
     *
     * @mbg.generated
     */
    public Float getCssTotalCharge() {
        return cssTotalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_total_charge
     *
     * @param cssTotalCharge the value for cs_statistics.css_total_charge
     *
     * @mbg.generated
     */
    public void setCssTotalCharge(Float cssTotalCharge) {
        this.cssTotalCharge = cssTotalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_total_power_consumption
     *
     * @return the value of cs_statistics.css_total_power_consumption
     *
     * @mbg.generated
     */
    public Float getCssTotalPowerConsumption() {
        return cssTotalPowerConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_total_power_consumption
     *
     * @param cssTotalPowerConsumption the value for cs_statistics.css_total_power_consumption
     *
     * @mbg.generated
     */
    public void setCssTotalPowerConsumption(Float cssTotalPowerConsumption) {
        this.cssTotalPowerConsumption = cssTotalPowerConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_total_run_time
     *
     * @return the value of cs_statistics.css_total_run_time
     *
     * @mbg.generated
     */
    public Long getCssTotalRunTime() {
        return cssTotalRunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_total_run_time
     *
     * @param cssTotalRunTime the value for cs_statistics.css_total_run_time
     *
     * @mbg.generated
     */
    public void setCssTotalRunTime(Long cssTotalRunTime) {
        this.cssTotalRunTime = cssTotalRunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_increment_mileage
     *
     * @return the value of cs_statistics.css_increment_mileage
     *
     * @mbg.generated
     */
    public Long getCssIncrementMileage() {
        return cssIncrementMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_increment_mileage
     *
     * @param cssIncrementMileage the value for cs_statistics.css_increment_mileage
     *
     * @mbg.generated
     */
    public void setCssIncrementMileage(Long cssIncrementMileage) {
        this.cssIncrementMileage = cssIncrementMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_access
     *
     * @return the value of cs_statistics.css_access
     *
     * @mbg.generated
     */
    public Integer getCssAccess() {
        return cssAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_access
     *
     * @param cssAccess the value for cs_statistics.css_access
     *
     * @mbg.generated
     */
    public void setCssAccess(Integer cssAccess) {
        this.cssAccess = cssAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_statistics.css_car_model
     *
     * @return the value of cs_statistics.css_car_model
     *
     * @mbg.generated
     */
    public Integer getCssCarModel() {
        return cssCarModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_statistics.css_car_model
     *
     * @param cssCarModel the value for cs_statistics.css_car_model
     *
     * @mbg.generated
     */
    public void setCssCarModel(Integer cssCarModel) {
        this.cssCarModel = cssCarModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CsStatistics other = (CsStatistics) that;
        return (this.getCssId() == null ? other.getCssId() == null : this.getCssId().equals(other.getCssId()))
            && (this.getCssTime() == null ? other.getCssTime() == null : this.getCssTime().equals(other.getCssTime()))
            && (this.getCssUnitTime() == null ? other.getCssUnitTime() == null : this.getCssUnitTime().equals(other.getCssUnitTime()))
            && (this.getCssRegisteredNum() == null ? other.getCssRegisteredNum() == null : this.getCssRegisteredNum().equals(other.getCssRegisteredNum()))
            && (this.getCssOnlineNum() == null ? other.getCssOnlineNum() == null : this.getCssOnlineNum().equals(other.getCssOnlineNum()))
            && (this.getCssOfflineNum() == null ? other.getCssOfflineNum() == null : this.getCssOfflineNum().equals(other.getCssOfflineNum()))
            && (this.getCssRunNum() == null ? other.getCssRunNum() == null : this.getCssRunNum().equals(other.getCssRunNum()))
            && (this.getCssChargingNum() == null ? other.getCssChargingNum() == null : this.getCssChargingNum().equals(other.getCssChargingNum()))
            && (this.getCssTotalMileage() == null ? other.getCssTotalMileage() == null : this.getCssTotalMileage().equals(other.getCssTotalMileage()))
            && (this.getCssTotalCharge() == null ? other.getCssTotalCharge() == null : this.getCssTotalCharge().equals(other.getCssTotalCharge()))
            && (this.getCssTotalPowerConsumption() == null ? other.getCssTotalPowerConsumption() == null : this.getCssTotalPowerConsumption().equals(other.getCssTotalPowerConsumption()))
            && (this.getCssTotalRunTime() == null ? other.getCssTotalRunTime() == null : this.getCssTotalRunTime().equals(other.getCssTotalRunTime()))
            && (this.getCssIncrementMileage() == null ? other.getCssIncrementMileage() == null : this.getCssIncrementMileage().equals(other.getCssIncrementMileage()))
            && (this.getCssAccess() == null ? other.getCssAccess() == null : this.getCssAccess().equals(other.getCssAccess()))
            && (this.getCssCarModel() == null ? other.getCssCarModel() == null : this.getCssCarModel().equals(other.getCssCarModel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCssId() == null) ? 0 : getCssId().hashCode());
        result = prime * result + ((getCssTime() == null) ? 0 : getCssTime().hashCode());
        result = prime * result + ((getCssUnitTime() == null) ? 0 : getCssUnitTime().hashCode());
        result = prime * result + ((getCssRegisteredNum() == null) ? 0 : getCssRegisteredNum().hashCode());
        result = prime * result + ((getCssOnlineNum() == null) ? 0 : getCssOnlineNum().hashCode());
        result = prime * result + ((getCssOfflineNum() == null) ? 0 : getCssOfflineNum().hashCode());
        result = prime * result + ((getCssRunNum() == null) ? 0 : getCssRunNum().hashCode());
        result = prime * result + ((getCssChargingNum() == null) ? 0 : getCssChargingNum().hashCode());
        result = prime * result + ((getCssTotalMileage() == null) ? 0 : getCssTotalMileage().hashCode());
        result = prime * result + ((getCssTotalCharge() == null) ? 0 : getCssTotalCharge().hashCode());
        result = prime * result + ((getCssTotalPowerConsumption() == null) ? 0 : getCssTotalPowerConsumption().hashCode());
        result = prime * result + ((getCssTotalRunTime() == null) ? 0 : getCssTotalRunTime().hashCode());
        result = prime * result + ((getCssIncrementMileage() == null) ? 0 : getCssIncrementMileage().hashCode());
        result = prime * result + ((getCssAccess() == null) ? 0 : getCssAccess().hashCode());
        result = prime * result + ((getCssCarModel() == null) ? 0 : getCssCarModel().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cssId=").append(cssId);
        sb.append(", cssTime=").append(cssTime);
        sb.append(", cssUnitTime=").append(cssUnitTime);
        sb.append(", cssRegisteredNum=").append(cssRegisteredNum);
        sb.append(", cssOnlineNum=").append(cssOnlineNum);
        sb.append(", cssOfflineNum=").append(cssOfflineNum);
        sb.append(", cssRunNum=").append(cssRunNum);
        sb.append(", cssChargingNum=").append(cssChargingNum);
        sb.append(", cssTotalMileage=").append(cssTotalMileage);
        sb.append(", cssTotalCharge=").append(cssTotalCharge);
        sb.append(", cssTotalPowerConsumption=").append(cssTotalPowerConsumption);
        sb.append(", cssTotalRunTime=").append(cssTotalRunTime);
        sb.append(", cssIncrementMileage=").append(cssIncrementMileage);
        sb.append(", cssAccess=").append(cssAccess);
        sb.append(", cssCarModel=").append(cssCarModel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}