package com.ccclubs.manage.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CsStatisticsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public CsStatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCssIdIsNull() {
            addCriterion("css_id is null");
            return (Criteria) this;
        }

        public Criteria andCssIdIsNotNull() {
            addCriterion("css_id is not null");
            return (Criteria) this;
        }

        public Criteria andCssIdEqualTo(Integer value) {
            addCriterion("css_id =", value, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdNotEqualTo(Integer value) {
            addCriterion("css_id <>", value, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdGreaterThan(Integer value) {
            addCriterion("css_id >", value, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("css_id >=", value, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdLessThan(Integer value) {
            addCriterion("css_id <", value, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdLessThanOrEqualTo(Integer value) {
            addCriterion("css_id <=", value, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdIn(List<Integer> values) {
            addCriterion("css_id in", values, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdNotIn(List<Integer> values) {
            addCriterion("css_id not in", values, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdBetween(Integer value1, Integer value2) {
            addCriterion("css_id between", value1, value2, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssIdNotBetween(Integer value1, Integer value2) {
            addCriterion("css_id not between", value1, value2, "cssId");
            return (Criteria) this;
        }

        public Criteria andCssTimeIsNull() {
            addCriterion("css_time is null");
            return (Criteria) this;
        }

        public Criteria andCssTimeIsNotNull() {
            addCriterion("css_time is not null");
            return (Criteria) this;
        }

        public Criteria andCssTimeEqualTo(Date value) {
            addCriterion("css_time =", value, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeNotEqualTo(Date value) {
            addCriterion("css_time <>", value, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeGreaterThan(Date value) {
            addCriterion("css_time >", value, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("css_time >=", value, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeLessThan(Date value) {
            addCriterion("css_time <", value, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeLessThanOrEqualTo(Date value) {
            addCriterion("css_time <=", value, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeIn(List<Date> values) {
            addCriterion("css_time in", values, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeNotIn(List<Date> values) {
            addCriterion("css_time not in", values, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeBetween(Date value1, Date value2) {
            addCriterion("css_time between", value1, value2, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssTimeNotBetween(Date value1, Date value2) {
            addCriterion("css_time not between", value1, value2, "cssTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeIsNull() {
            addCriterion("css_unit_time is null");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeIsNotNull() {
            addCriterion("css_unit_time is not null");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeEqualTo(Long value) {
            addCriterion("css_unit_time =", value, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeNotEqualTo(Long value) {
            addCriterion("css_unit_time <>", value, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeGreaterThan(Long value) {
            addCriterion("css_unit_time >", value, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("css_unit_time >=", value, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeLessThan(Long value) {
            addCriterion("css_unit_time <", value, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeLessThanOrEqualTo(Long value) {
            addCriterion("css_unit_time <=", value, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeIn(List<Long> values) {
            addCriterion("css_unit_time in", values, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeNotIn(List<Long> values) {
            addCriterion("css_unit_time not in", values, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeBetween(Long value1, Long value2) {
            addCriterion("css_unit_time between", value1, value2, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssUnitTimeNotBetween(Long value1, Long value2) {
            addCriterion("css_unit_time not between", value1, value2, "cssUnitTime");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumIsNull() {
            addCriterion("css_registered_num is null");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumIsNotNull() {
            addCriterion("css_registered_num is not null");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumEqualTo(Integer value) {
            addCriterion("css_registered_num =", value, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumNotEqualTo(Integer value) {
            addCriterion("css_registered_num <>", value, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumGreaterThan(Integer value) {
            addCriterion("css_registered_num >", value, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("css_registered_num >=", value, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumLessThan(Integer value) {
            addCriterion("css_registered_num <", value, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumLessThanOrEqualTo(Integer value) {
            addCriterion("css_registered_num <=", value, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumIn(List<Integer> values) {
            addCriterion("css_registered_num in", values, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumNotIn(List<Integer> values) {
            addCriterion("css_registered_num not in", values, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumBetween(Integer value1, Integer value2) {
            addCriterion("css_registered_num between", value1, value2, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssRegisteredNumNotBetween(Integer value1, Integer value2) {
            addCriterion("css_registered_num not between", value1, value2, "cssRegisteredNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumIsNull() {
            addCriterion("css_online_num is null");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumIsNotNull() {
            addCriterion("css_online_num is not null");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumEqualTo(Integer value) {
            addCriterion("css_online_num =", value, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumNotEqualTo(Integer value) {
            addCriterion("css_online_num <>", value, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumGreaterThan(Integer value) {
            addCriterion("css_online_num >", value, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("css_online_num >=", value, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumLessThan(Integer value) {
            addCriterion("css_online_num <", value, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumLessThanOrEqualTo(Integer value) {
            addCriterion("css_online_num <=", value, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumIn(List<Integer> values) {
            addCriterion("css_online_num in", values, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumNotIn(List<Integer> values) {
            addCriterion("css_online_num not in", values, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumBetween(Integer value1, Integer value2) {
            addCriterion("css_online_num between", value1, value2, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOnlineNumNotBetween(Integer value1, Integer value2) {
            addCriterion("css_online_num not between", value1, value2, "cssOnlineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumIsNull() {
            addCriterion("css_offline_num is null");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumIsNotNull() {
            addCriterion("css_offline_num is not null");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumEqualTo(Integer value) {
            addCriterion("css_offline_num =", value, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumNotEqualTo(Integer value) {
            addCriterion("css_offline_num <>", value, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumGreaterThan(Integer value) {
            addCriterion("css_offline_num >", value, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("css_offline_num >=", value, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumLessThan(Integer value) {
            addCriterion("css_offline_num <", value, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumLessThanOrEqualTo(Integer value) {
            addCriterion("css_offline_num <=", value, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumIn(List<Integer> values) {
            addCriterion("css_offline_num in", values, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumNotIn(List<Integer> values) {
            addCriterion("css_offline_num not in", values, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumBetween(Integer value1, Integer value2) {
            addCriterion("css_offline_num between", value1, value2, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssOfflineNumNotBetween(Integer value1, Integer value2) {
            addCriterion("css_offline_num not between", value1, value2, "cssOfflineNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumIsNull() {
            addCriterion("css_run_num is null");
            return (Criteria) this;
        }

        public Criteria andCssRunNumIsNotNull() {
            addCriterion("css_run_num is not null");
            return (Criteria) this;
        }

        public Criteria andCssRunNumEqualTo(Integer value) {
            addCriterion("css_run_num =", value, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumNotEqualTo(Integer value) {
            addCriterion("css_run_num <>", value, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumGreaterThan(Integer value) {
            addCriterion("css_run_num >", value, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("css_run_num >=", value, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumLessThan(Integer value) {
            addCriterion("css_run_num <", value, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumLessThanOrEqualTo(Integer value) {
            addCriterion("css_run_num <=", value, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumIn(List<Integer> values) {
            addCriterion("css_run_num in", values, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumNotIn(List<Integer> values) {
            addCriterion("css_run_num not in", values, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumBetween(Integer value1, Integer value2) {
            addCriterion("css_run_num between", value1, value2, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssRunNumNotBetween(Integer value1, Integer value2) {
            addCriterion("css_run_num not between", value1, value2, "cssRunNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumIsNull() {
            addCriterion("css_charging_num is null");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumIsNotNull() {
            addCriterion("css_charging_num is not null");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumEqualTo(Integer value) {
            addCriterion("css_charging_num =", value, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumNotEqualTo(Integer value) {
            addCriterion("css_charging_num <>", value, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumGreaterThan(Integer value) {
            addCriterion("css_charging_num >", value, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("css_charging_num >=", value, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumLessThan(Integer value) {
            addCriterion("css_charging_num <", value, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumLessThanOrEqualTo(Integer value) {
            addCriterion("css_charging_num <=", value, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumIn(List<Integer> values) {
            addCriterion("css_charging_num in", values, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumNotIn(List<Integer> values) {
            addCriterion("css_charging_num not in", values, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumBetween(Integer value1, Integer value2) {
            addCriterion("css_charging_num between", value1, value2, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssChargingNumNotBetween(Integer value1, Integer value2) {
            addCriterion("css_charging_num not between", value1, value2, "cssChargingNum");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageIsNull() {
            addCriterion("css_total_mileage is null");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageIsNotNull() {
            addCriterion("css_total_mileage is not null");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageEqualTo(Float value) {
            addCriterion("css_total_mileage =", value, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageNotEqualTo(Float value) {
            addCriterion("css_total_mileage <>", value, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageGreaterThan(Float value) {
            addCriterion("css_total_mileage >", value, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageGreaterThanOrEqualTo(Float value) {
            addCriterion("css_total_mileage >=", value, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageLessThan(Float value) {
            addCriterion("css_total_mileage <", value, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageLessThanOrEqualTo(Float value) {
            addCriterion("css_total_mileage <=", value, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageIn(List<Float> values) {
            addCriterion("css_total_mileage in", values, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageNotIn(List<Float> values) {
            addCriterion("css_total_mileage not in", values, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageBetween(Float value1, Float value2) {
            addCriterion("css_total_mileage between", value1, value2, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalMileageNotBetween(Float value1, Float value2) {
            addCriterion("css_total_mileage not between", value1, value2, "cssTotalMileage");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeIsNull() {
            addCriterion("css_total_charge is null");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeIsNotNull() {
            addCriterion("css_total_charge is not null");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeEqualTo(Float value) {
            addCriterion("css_total_charge =", value, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeNotEqualTo(Float value) {
            addCriterion("css_total_charge <>", value, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeGreaterThan(Float value) {
            addCriterion("css_total_charge >", value, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeGreaterThanOrEqualTo(Float value) {
            addCriterion("css_total_charge >=", value, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeLessThan(Float value) {
            addCriterion("css_total_charge <", value, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeLessThanOrEqualTo(Float value) {
            addCriterion("css_total_charge <=", value, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeIn(List<Float> values) {
            addCriterion("css_total_charge in", values, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeNotIn(List<Float> values) {
            addCriterion("css_total_charge not in", values, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeBetween(Float value1, Float value2) {
            addCriterion("css_total_charge between", value1, value2, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalChargeNotBetween(Float value1, Float value2) {
            addCriterion("css_total_charge not between", value1, value2, "cssTotalCharge");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionIsNull() {
            addCriterion("css_total_power_consumption is null");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionIsNotNull() {
            addCriterion("css_total_power_consumption is not null");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionEqualTo(Float value) {
            addCriterion("css_total_power_consumption =", value, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionNotEqualTo(Float value) {
            addCriterion("css_total_power_consumption <>", value, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionGreaterThan(Float value) {
            addCriterion("css_total_power_consumption >", value, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionGreaterThanOrEqualTo(Float value) {
            addCriterion("css_total_power_consumption >=", value, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionLessThan(Float value) {
            addCriterion("css_total_power_consumption <", value, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionLessThanOrEqualTo(Float value) {
            addCriterion("css_total_power_consumption <=", value, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionIn(List<Float> values) {
            addCriterion("css_total_power_consumption in", values, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionNotIn(List<Float> values) {
            addCriterion("css_total_power_consumption not in", values, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionBetween(Float value1, Float value2) {
            addCriterion("css_total_power_consumption between", value1, value2, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalPowerConsumptionNotBetween(Float value1, Float value2) {
            addCriterion("css_total_power_consumption not between", value1, value2, "cssTotalPowerConsumption");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeIsNull() {
            addCriterion("css_total_run_time is null");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeIsNotNull() {
            addCriterion("css_total_run_time is not null");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeEqualTo(Long value) {
            addCriterion("css_total_run_time =", value, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeNotEqualTo(Long value) {
            addCriterion("css_total_run_time <>", value, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeGreaterThan(Long value) {
            addCriterion("css_total_run_time >", value, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("css_total_run_time >=", value, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeLessThan(Long value) {
            addCriterion("css_total_run_time <", value, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeLessThanOrEqualTo(Long value) {
            addCriterion("css_total_run_time <=", value, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeIn(List<Long> values) {
            addCriterion("css_total_run_time in", values, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeNotIn(List<Long> values) {
            addCriterion("css_total_run_time not in", values, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeBetween(Long value1, Long value2) {
            addCriterion("css_total_run_time between", value1, value2, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssTotalRunTimeNotBetween(Long value1, Long value2) {
            addCriterion("css_total_run_time not between", value1, value2, "cssTotalRunTime");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageIsNull() {
            addCriterion("css_increment_mileage is null");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageIsNotNull() {
            addCriterion("css_increment_mileage is not null");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageEqualTo(Long value) {
            addCriterion("css_increment_mileage =", value, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageNotEqualTo(Long value) {
            addCriterion("css_increment_mileage <>", value, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageGreaterThan(Long value) {
            addCriterion("css_increment_mileage >", value, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageGreaterThanOrEqualTo(Long value) {
            addCriterion("css_increment_mileage >=", value, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageLessThan(Long value) {
            addCriterion("css_increment_mileage <", value, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageLessThanOrEqualTo(Long value) {
            addCriterion("css_increment_mileage <=", value, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageIn(List<Long> values) {
            addCriterion("css_increment_mileage in", values, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageNotIn(List<Long> values) {
            addCriterion("css_increment_mileage not in", values, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageBetween(Long value1, Long value2) {
            addCriterion("css_increment_mileage between", value1, value2, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssIncrementMileageNotBetween(Long value1, Long value2) {
            addCriterion("css_increment_mileage not between", value1, value2, "cssIncrementMileage");
            return (Criteria) this;
        }

        public Criteria andCssAccessIsNull() {
            addCriterion("css_access is null");
            return (Criteria) this;
        }

        public Criteria andCssAccessIsNotNull() {
            addCriterion("css_access is not null");
            return (Criteria) this;
        }

        public Criteria andCssAccessEqualTo(Integer value) {
            addCriterion("css_access =", value, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessNotEqualTo(Integer value) {
            addCriterion("css_access <>", value, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessGreaterThan(Integer value) {
            addCriterion("css_access >", value, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessGreaterThanOrEqualTo(Integer value) {
            addCriterion("css_access >=", value, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessLessThan(Integer value) {
            addCriterion("css_access <", value, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessLessThanOrEqualTo(Integer value) {
            addCriterion("css_access <=", value, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessIn(List<Integer> values) {
            addCriterion("css_access in", values, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessNotIn(List<Integer> values) {
            addCriterion("css_access not in", values, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessBetween(Integer value1, Integer value2) {
            addCriterion("css_access between", value1, value2, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssAccessNotBetween(Integer value1, Integer value2) {
            addCriterion("css_access not between", value1, value2, "cssAccess");
            return (Criteria) this;
        }

        public Criteria andCssCarModelIsNull() {
            addCriterion("css_car_model is null");
            return (Criteria) this;
        }

        public Criteria andCssCarModelIsNotNull() {
            addCriterion("css_car_model is not null");
            return (Criteria) this;
        }

        public Criteria andCssCarModelEqualTo(Integer value) {
            addCriterion("css_car_model =", value, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelNotEqualTo(Integer value) {
            addCriterion("css_car_model <>", value, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelGreaterThan(Integer value) {
            addCriterion("css_car_model >", value, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelGreaterThanOrEqualTo(Integer value) {
            addCriterion("css_car_model >=", value, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelLessThan(Integer value) {
            addCriterion("css_car_model <", value, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelLessThanOrEqualTo(Integer value) {
            addCriterion("css_car_model <=", value, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelIn(List<Integer> values) {
            addCriterion("css_car_model in", values, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelNotIn(List<Integer> values) {
            addCriterion("css_car_model not in", values, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelBetween(Integer value1, Integer value2) {
            addCriterion("css_car_model between", value1, value2, "cssCarModel");
            return (Criteria) this;
        }

        public Criteria andCssCarModelNotBetween(Integer value1, Integer value2) {
            addCriterion("css_car_model not between", value1, value2, "cssCarModel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_statistics
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_statistics
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}