package com.ccclubs.olap.orm.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by Administrator on 2017/9/7 0007.
 */
public class SocMilesBasicZhifaExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public SocMilesBasicZhifaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public void or(SocMilesBasicZhifaExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public SocMilesBasicZhifaExample.Criteria or() {
        SocMilesBasicZhifaExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public SocMilesBasicZhifaExample.Criteria createCriteria() {
        SocMilesBasicZhifaExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected SocMilesBasicZhifaExample.Criteria createCriteriaInternal() {
        SocMilesBasicZhifaExample.Criteria criteria = new SocMilesBasicZhifaExample.Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new SocMilesBasicZhifaExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new SocMilesBasicZhifaExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new SocMilesBasicZhifaExample.Criterion(condition, value1, value2));
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberIsNull() {
            addCriterion("cs_number is null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberIsNotNull() {
            addCriterion("cs_number is not null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberEqualTo(String value) {
            addCriterion("cs_number =", value, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberNotEqualTo(String value) {
            addCriterion("cs_number <>", value, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberGreaterThan(String value) {
            addCriterion("cs_number >", value, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberGreaterThanOrEqualTo(String value) {
            addCriterion("cs_number >=", value, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberLessThan(String value) {
            addCriterion("cs_number <", value, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberLessThanOrEqualTo(String value) {
            addCriterion("cs_number <=", value, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberLike(String value) {
            addCriterion("cs_number like", value, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberNotLike(String value) {
            addCriterion("cs_number not like", value, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberIn(List<String> values) {
            addCriterion("cs_number in", values, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberNotIn(List<String> values) {
            addCriterion("cs_number not in", values, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberBetween(String value1, String value2) {
            addCriterion("cs_number between", value1, value2, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andCsNumberNotBetween(String value1, String value2) {
            addCriterion("cs_number not between", value1, value2, "csNumber");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoIsNull() {
            addCriterion("row_no is null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoIsNotNull() {
            addCriterion("row_no is not null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoEqualTo(Integer value) {
            addCriterion("row_no =", value, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoNotEqualTo(Integer value) {
            addCriterion("row_no <>", value, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoGreaterThan(Integer value) {
            addCriterion("row_no >", value, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("row_no >=", value, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoLessThan(Integer value) {
            addCriterion("row_no <", value, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoLessThanOrEqualTo(Integer value) {
            addCriterion("row_no <=", value, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoIn(List<Integer> values) {
            addCriterion("row_no in", values, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoNotIn(List<Integer> values) {
            addCriterion("row_no not in", values, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoBetween(Integer value1, Integer value2) {
            addCriterion("row_no between", value1, value2, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andRowNoNotBetween(Integer value1, Integer value2) {
            addCriterion("row_no not between", value1, value2, "rowNo");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocIsNull() {
            addCriterion("start_soc is null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocIsNotNull() {
            addCriterion("start_soc is not null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocEqualTo(Integer value) {
            addCriterion("start_soc =", value, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocNotEqualTo(Integer value) {
            addCriterion("start_soc <>", value, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocGreaterThan(Integer value) {
            addCriterion("start_soc >", value, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocGreaterThanOrEqualTo(Integer value) {
            addCriterion("start_soc >=", value, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocLessThan(Integer value) {
            addCriterion("start_soc <", value, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocLessThanOrEqualTo(Integer value) {
            addCriterion("start_soc <=", value, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocIn(List<Integer> values) {
            addCriterion("start_soc in", values, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocNotIn(List<Integer> values) {
            addCriterion("start_soc not in", values, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocBetween(Integer value1, Integer value2) {
            addCriterion("start_soc between", value1, value2, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartSocNotBetween(Integer value1, Integer value2) {
            addCriterion("start_soc not between", value1, value2, "startSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocIsNull() {
            addCriterion("end_soc is null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocIsNotNull() {
            addCriterion("end_soc is not null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocEqualTo(BigDecimal value) {
            addCriterion("end_soc =", value, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocNotEqualTo(Integer value) {
            addCriterion("end_soc <>", value, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocGreaterThan(Integer value) {
            addCriterion("end_soc >", value, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocGreaterThanOrEqualTo(Integer value) {
            addCriterion("end_soc >=", value, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocLessThan(Integer value) {
            addCriterion("end_soc <", value, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocLessThanOrEqualTo(Integer value) {
            addCriterion("end_soc <=", value, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocIn(List<Integer> values) {
            addCriterion("end_soc in", values, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocNotIn(List<Integer> values) {
            addCriterion("end_soc not in", values, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocBetween(Integer value1, Integer value2) {
            addCriterion("end_soc between", value1, value2, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndSocNotBetween(Integer value1, Integer value2) {
            addCriterion("end_soc not between", value1, value2, "endSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocIsNull() {
            addCriterion("changed_soc is null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocIsNotNull() {
            addCriterion("changed_soc is not null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocEqualTo(Integer value) {
            addCriterion("changed_soc =", value, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocNotEqualTo(Integer value) {
            addCriterion("changed_soc <>", value, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocGreaterThan(Integer value) {
            addCriterion("changed_soc >", value, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocGreaterThanOrEqualTo(Integer value) {
            addCriterion("changed_soc >=", value, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocLessThan(Integer value) {
            addCriterion("changed_soc <", value, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocLessThanOrEqualTo(Integer value) {
            addCriterion("changed_soc <=", value, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocIn(List<Integer> values) {
            addCriterion("changed_soc in", values, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocNotIn(List<Integer> values) {
            addCriterion("changed_soc not in", values, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocBetween(Integer value1, Integer value2) {
            addCriterion("changed_soc between", value1, value2, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andChangedSocNotBetween(Integer value1, Integer value2) {
            addCriterion("changed_soc not between", value1, value2, "changedSoc");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeEqualTo(String value) {
            addCriterion("start_time =", value, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("start_time <>", value, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeGreaterThan(String value) {
            addCriterion("start_time >", value, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("start_time >=", value, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeLessThan(String value) {
            addCriterion("start_time <", value, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("start_time <=", value, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeIn(List<String> values) {
            addCriterion("start_time in", values, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("start_time not in", values, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeEqualTo(String value) {
            addCriterion("end_time =", value, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("end_time <>", value, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeGreaterThan(String value) {
            addCriterion("end_time >", value, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("end_time >=", value, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeLessThan(String value) {
            addCriterion("end_time <", value, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("end_time <=", value, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeIn(List<String> values) {
            addCriterion("end_time in", values, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("end_time not in", values, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsIsNull() {
            addCriterion("pace_timemills is null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsIsNotNull() {
            addCriterion("pace_timemills is not null");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsEqualTo(Long value) {
            addCriterion("pace_timemills =", value, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsNotEqualTo(Long value) {
            addCriterion("pace_timemills <>", value, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsGreaterThan(Long value) {
            addCriterion("pace_timemills >", value, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsGreaterThanOrEqualTo(Long value) {
            addCriterion("pace_timemills >=", value, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsLessThan(Long value) {
            addCriterion("pace_timemills <", value, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsLessThanOrEqualTo(Long value) {
            addCriterion("pace_timemills <=", value, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsIn(List<Long> values) {
            addCriterion("pace_timemills in", values, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsNotIn(List<Long> values) {
            addCriterion("pace_timemills not in", values, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsBetween(Long value1, Long value2) {
            addCriterion("pace_timemills between", value1, value2, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }

        public SocMilesBasicZhifaExample.Criteria andPaceTimemillsNotBetween(Long value1, Long value2) {
            addCriterion("pace_timemills not between", value1, value2, "paceTimemills");
            return (SocMilesBasicZhifaExample.Criteria) this;
        }


    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_index_report
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends SocMilesBasicZhifaExample.GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_index_report
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }


}
