package com.ccclubs.pub.orm.model;

import java.io.Serializable;

public class VerSoftHardware implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_soft_hardware.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_soft_hardware.ver_no
     *
     * @mbg.generated
     */
    private String verNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_soft_hardware.des
     *
     * @mbg.generated
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_soft_hardware.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ver_soft_hardware
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_soft_hardware.id
     *
     * @return the value of ver_soft_hardware.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_soft_hardware.id
     *
     * @param id the value for ver_soft_hardware.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_soft_hardware.ver_no
     *
     * @return the value of ver_soft_hardware.ver_no
     *
     * @mbg.generated
     */
    public String getVerNo() {
        return verNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_soft_hardware.ver_no
     *
     * @param verNo the value for ver_soft_hardware.ver_no
     *
     * @mbg.generated
     */
    public void setVerNo(String verNo) {
        this.verNo = verNo == null ? null : verNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_soft_hardware.des
     *
     * @return the value of ver_soft_hardware.des
     *
     * @mbg.generated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_soft_hardware.des
     *
     * @param des the value for ver_soft_hardware.des
     *
     * @mbg.generated
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_soft_hardware.type
     *
     * @return the value of ver_soft_hardware.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_soft_hardware.type
     *
     * @param type the value for ver_soft_hardware.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_soft_hardware
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VerSoftHardware other = (VerSoftHardware) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVerNo() == null ? other.getVerNo() == null : this.getVerNo().equals(other.getVerNo()))
            && (this.getDes() == null ? other.getDes() == null : this.getDes().equals(other.getDes()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_soft_hardware
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVerNo() == null) ? 0 : getVerNo().hashCode());
        result = prime * result + ((getDes() == null) ? 0 : getDes().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_soft_hardware
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", verNo=").append(verNo);
        sb.append(", des=").append(des);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}