package com.ccclubs.pub.orm.model;

import java.util.ArrayList;
import java.util.List;

public class VerUpgradeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public VerUpgradeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdIsNull() {
            addCriterion("soft_ver_id is null");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdIsNotNull() {
            addCriterion("soft_ver_id is not null");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdEqualTo(Integer value) {
            addCriterion("soft_ver_id =", value, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdNotEqualTo(Integer value) {
            addCriterion("soft_ver_id <>", value, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdGreaterThan(Integer value) {
            addCriterion("soft_ver_id >", value, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("soft_ver_id >=", value, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdLessThan(Integer value) {
            addCriterion("soft_ver_id <", value, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdLessThanOrEqualTo(Integer value) {
            addCriterion("soft_ver_id <=", value, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdIn(List<Integer> values) {
            addCriterion("soft_ver_id in", values, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdNotIn(List<Integer> values) {
            addCriterion("soft_ver_id not in", values, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdBetween(Integer value1, Integer value2) {
            addCriterion("soft_ver_id between", value1, value2, "softVerId");
            return (Criteria) this;
        }

        public Criteria andSoftVerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("soft_ver_id not between", value1, value2, "softVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdIsNull() {
            addCriterion("hard_ver_id is null");
            return (Criteria) this;
        }

        public Criteria andHardVerIdIsNotNull() {
            addCriterion("hard_ver_id is not null");
            return (Criteria) this;
        }

        public Criteria andHardVerIdEqualTo(Integer value) {
            addCriterion("hard_ver_id =", value, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdNotEqualTo(Integer value) {
            addCriterion("hard_ver_id <>", value, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdGreaterThan(Integer value) {
            addCriterion("hard_ver_id >", value, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hard_ver_id >=", value, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdLessThan(Integer value) {
            addCriterion("hard_ver_id <", value, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdLessThanOrEqualTo(Integer value) {
            addCriterion("hard_ver_id <=", value, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdIn(List<Integer> values) {
            addCriterion("hard_ver_id in", values, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdNotIn(List<Integer> values) {
            addCriterion("hard_ver_id not in", values, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdBetween(Integer value1, Integer value2) {
            addCriterion("hard_ver_id between", value1, value2, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andHardVerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hard_ver_id not between", value1, value2, "hardVerId");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNull() {
            addCriterion("model_id is null");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNotNull() {
            addCriterion("model_id is not null");
            return (Criteria) this;
        }

        public Criteria andModelIdEqualTo(Integer value) {
            addCriterion("model_id =", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotEqualTo(Integer value) {
            addCriterion("model_id <>", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThan(Integer value) {
            addCriterion("model_id >", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("model_id >=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThan(Integer value) {
            addCriterion("model_id <", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThanOrEqualTo(Integer value) {
            addCriterion("model_id <=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdIn(List<Integer> values) {
            addCriterion("model_id in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotIn(List<Integer> values) {
            addCriterion("model_id not in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdBetween(Integer value1, Integer value2) {
            addCriterion("model_id between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("model_id not between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andTelTypeIsNull() {
            addCriterion("tel_type is null");
            return (Criteria) this;
        }

        public Criteria andTelTypeIsNotNull() {
            addCriterion("tel_type is not null");
            return (Criteria) this;
        }

        public Criteria andTelTypeEqualTo(Integer value) {
            addCriterion("tel_type =", value, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeNotEqualTo(Integer value) {
            addCriterion("tel_type <>", value, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeGreaterThan(Integer value) {
            addCriterion("tel_type >", value, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("tel_type >=", value, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeLessThan(Integer value) {
            addCriterion("tel_type <", value, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeLessThanOrEqualTo(Integer value) {
            addCriterion("tel_type <=", value, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeIn(List<Integer> values) {
            addCriterion("tel_type in", values, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeNotIn(List<Integer> values) {
            addCriterion("tel_type not in", values, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeBetween(Integer value1, Integer value2) {
            addCriterion("tel_type between", value1, value2, "telType");
            return (Criteria) this;
        }

        public Criteria andTelTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("tel_type not between", value1, value2, "telType");
            return (Criteria) this;
        }

        public Criteria andTelModelIsNull() {
            addCriterion("tel_model is null");
            return (Criteria) this;
        }

        public Criteria andTelModelIsNotNull() {
            addCriterion("tel_model is not null");
            return (Criteria) this;
        }

        public Criteria andTelModelEqualTo(String value) {
            addCriterion("tel_model =", value, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelNotEqualTo(String value) {
            addCriterion("tel_model <>", value, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelGreaterThan(String value) {
            addCriterion("tel_model >", value, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelGreaterThanOrEqualTo(String value) {
            addCriterion("tel_model >=", value, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelLessThan(String value) {
            addCriterion("tel_model <", value, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelLessThanOrEqualTo(String value) {
            addCriterion("tel_model <=", value, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelLike(String value) {
            addCriterion("tel_model like", value, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelNotLike(String value) {
            addCriterion("tel_model not like", value, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelIn(List<String> values) {
            addCriterion("tel_model in", values, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelNotIn(List<String> values) {
            addCriterion("tel_model not in", values, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelBetween(String value1, String value2) {
            addCriterion("tel_model between", value1, value2, "telModel");
            return (Criteria) this;
        }

        public Criteria andTelModelNotBetween(String value1, String value2) {
            addCriterion("tel_model not between", value1, value2, "telModel");
            return (Criteria) this;
        }

        public Criteria andInnerVerIsNull() {
            addCriterion("inner_ver is null");
            return (Criteria) this;
        }

        public Criteria andInnerVerIsNotNull() {
            addCriterion("inner_ver is not null");
            return (Criteria) this;
        }

        public Criteria andInnerVerEqualTo(String value) {
            addCriterion("inner_ver =", value, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerNotEqualTo(String value) {
            addCriterion("inner_ver <>", value, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerGreaterThan(String value) {
            addCriterion("inner_ver >", value, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerGreaterThanOrEqualTo(String value) {
            addCriterion("inner_ver >=", value, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerLessThan(String value) {
            addCriterion("inner_ver <", value, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerLessThanOrEqualTo(String value) {
            addCriterion("inner_ver <=", value, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerLike(String value) {
            addCriterion("inner_ver like", value, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerNotLike(String value) {
            addCriterion("inner_ver not like", value, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerIn(List<String> values) {
            addCriterion("inner_ver in", values, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerNotIn(List<String> values) {
            addCriterion("inner_ver not in", values, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerBetween(String value1, String value2) {
            addCriterion("inner_ver between", value1, value2, "innerVer");
            return (Criteria) this;
        }

        public Criteria andInnerVerNotBetween(String value1, String value2) {
            addCriterion("inner_ver not between", value1, value2, "innerVer");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNull() {
            addCriterion("is_open is null");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNotNull() {
            addCriterion("is_open is not null");
            return (Criteria) this;
        }

        public Criteria andIsOpenEqualTo(Byte value) {
            addCriterion("is_open =", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotEqualTo(Byte value) {
            addCriterion("is_open <>", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThan(Byte value) {
            addCriterion("is_open >", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_open >=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThan(Byte value) {
            addCriterion("is_open <", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThanOrEqualTo(Byte value) {
            addCriterion("is_open <=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenIn(List<Byte> values) {
            addCriterion("is_open in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotIn(List<Byte> values) {
            addCriterion("is_open not in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenBetween(Byte value1, Byte value2) {
            addCriterion("is_open between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotBetween(Byte value1, Byte value2) {
            addCriterion("is_open not between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andDesIsNull() {
            addCriterion("des is null");
            return (Criteria) this;
        }

        public Criteria andDesIsNotNull() {
            addCriterion("des is not null");
            return (Criteria) this;
        }

        public Criteria andDesEqualTo(String value) {
            addCriterion("des =", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotEqualTo(String value) {
            addCriterion("des <>", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThan(String value) {
            addCriterion("des >", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThanOrEqualTo(String value) {
            addCriterion("des >=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThan(String value) {
            addCriterion("des <", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThanOrEqualTo(String value) {
            addCriterion("des <=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLike(String value) {
            addCriterion("des like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotLike(String value) {
            addCriterion("des not like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesIn(List<String> values) {
            addCriterion("des in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotIn(List<String> values) {
            addCriterion("des not in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesBetween(String value1, String value2) {
            addCriterion("des between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotBetween(String value1, String value2) {
            addCriterion("des not between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andUpVerNoIsNull() {
            addCriterion("up_ver_no is null");
            return (Criteria) this;
        }

        public Criteria andUpVerNoIsNotNull() {
            addCriterion("up_ver_no is not null");
            return (Criteria) this;
        }

        public Criteria andUpVerNoEqualTo(String value) {
            addCriterion("up_ver_no =", value, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoNotEqualTo(String value) {
            addCriterion("up_ver_no <>", value, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoGreaterThan(String value) {
            addCriterion("up_ver_no >", value, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoGreaterThanOrEqualTo(String value) {
            addCriterion("up_ver_no >=", value, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoLessThan(String value) {
            addCriterion("up_ver_no <", value, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoLessThanOrEqualTo(String value) {
            addCriterion("up_ver_no <=", value, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoLike(String value) {
            addCriterion("up_ver_no like", value, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoNotLike(String value) {
            addCriterion("up_ver_no not like", value, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoIn(List<String> values) {
            addCriterion("up_ver_no in", values, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoNotIn(List<String> values) {
            addCriterion("up_ver_no not in", values, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoBetween(String value1, String value2) {
            addCriterion("up_ver_no between", value1, value2, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andUpVerNoNotBetween(String value1, String value2) {
            addCriterion("up_ver_no not between", value1, value2, "upVerNo");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdIsNull() {
            addCriterion("ser_ftp_id is null");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdIsNotNull() {
            addCriterion("ser_ftp_id is not null");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdEqualTo(Integer value) {
            addCriterion("ser_ftp_id =", value, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdNotEqualTo(Integer value) {
            addCriterion("ser_ftp_id <>", value, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdGreaterThan(Integer value) {
            addCriterion("ser_ftp_id >", value, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ser_ftp_id >=", value, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdLessThan(Integer value) {
            addCriterion("ser_ftp_id <", value, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdLessThanOrEqualTo(Integer value) {
            addCriterion("ser_ftp_id <=", value, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdIn(List<Integer> values) {
            addCriterion("ser_ftp_id in", values, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdNotIn(List<Integer> values) {
            addCriterion("ser_ftp_id not in", values, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdBetween(Integer value1, Integer value2) {
            addCriterion("ser_ftp_id between", value1, value2, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andSerFtpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ser_ftp_id not between", value1, value2, "serFtpId");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutIsNull() {
            addCriterion("per_timeout is null");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutIsNotNull() {
            addCriterion("per_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutEqualTo(Integer value) {
            addCriterion("per_timeout =", value, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutNotEqualTo(Integer value) {
            addCriterion("per_timeout <>", value, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutGreaterThan(Integer value) {
            addCriterion("per_timeout >", value, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("per_timeout >=", value, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutLessThan(Integer value) {
            addCriterion("per_timeout <", value, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("per_timeout <=", value, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutIn(List<Integer> values) {
            addCriterion("per_timeout in", values, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutNotIn(List<Integer> values) {
            addCriterion("per_timeout not in", values, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("per_timeout between", value1, value2, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("per_timeout not between", value1, value2, "perTimeout");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleIsNull() {
            addCriterion("per_max_vehicle is null");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleIsNotNull() {
            addCriterion("per_max_vehicle is not null");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleEqualTo(Integer value) {
            addCriterion("per_max_vehicle =", value, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleNotEqualTo(Integer value) {
            addCriterion("per_max_vehicle <>", value, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleGreaterThan(Integer value) {
            addCriterion("per_max_vehicle >", value, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleGreaterThanOrEqualTo(Integer value) {
            addCriterion("per_max_vehicle >=", value, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleLessThan(Integer value) {
            addCriterion("per_max_vehicle <", value, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleLessThanOrEqualTo(Integer value) {
            addCriterion("per_max_vehicle <=", value, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleIn(List<Integer> values) {
            addCriterion("per_max_vehicle in", values, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleNotIn(List<Integer> values) {
            addCriterion("per_max_vehicle not in", values, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleBetween(Integer value1, Integer value2) {
            addCriterion("per_max_vehicle between", value1, value2, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andPerMaxVehicleNotBetween(Integer value1, Integer value2) {
            addCriterion("per_max_vehicle not between", value1, value2, "perMaxVehicle");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("file_name is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("file_name is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("file_name =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("file_name <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("file_name >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("file_name >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("file_name <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("file_name <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("file_name like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("file_name not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("file_name in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("file_name not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("file_name between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("file_name not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagIsNull() {
            addCriterion("turn_off_flag is null");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagIsNotNull() {
            addCriterion("turn_off_flag is not null");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagEqualTo(Byte value) {
            addCriterion("turn_off_flag =", value, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagNotEqualTo(Byte value) {
            addCriterion("turn_off_flag <>", value, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagGreaterThan(Byte value) {
            addCriterion("turn_off_flag >", value, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("turn_off_flag >=", value, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagLessThan(Byte value) {
            addCriterion("turn_off_flag <", value, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagLessThanOrEqualTo(Byte value) {
            addCriterion("turn_off_flag <=", value, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagIn(List<Byte> values) {
            addCriterion("turn_off_flag in", values, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagNotIn(List<Byte> values) {
            addCriterion("turn_off_flag not in", values, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagBetween(Byte value1, Byte value2) {
            addCriterion("turn_off_flag between", value1, value2, "turnOffFlag");
            return (Criteria) this;
        }

        public Criteria andTurnOffFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("turn_off_flag not between", value1, value2, "turnOffFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ver_upgrade
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}