package com.ccclubs.pub.orm.model;

import java.io.Serializable;

public class VerUpManage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_up_manage.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_up_manage.status_upgrade
     *
     * @mbg.generated
     */
    private Integer statusUpgrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_up_manage.ver_cur_id
     *
     * @mbg.generated
     */
    private Integer verCurId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_up_manage.model_id
     *
     * @mbg.generated
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_up_manage.vehicle_id
     *
     * @mbg.generated
     */
    private Integer vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ver_up_manage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_up_manage.id
     *
     * @return the value of ver_up_manage.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_up_manage.id
     *
     * @param id the value for ver_up_manage.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_up_manage.status_upgrade
     *
     * @return the value of ver_up_manage.status_upgrade
     *
     * @mbg.generated
     */
    public Integer getStatusUpgrade() {
        return statusUpgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_up_manage.status_upgrade
     *
     * @param statusUpgrade the value for ver_up_manage.status_upgrade
     *
     * @mbg.generated
     */
    public void setStatusUpgrade(Integer statusUpgrade) {
        this.statusUpgrade = statusUpgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_up_manage.ver_cur_id
     *
     * @return the value of ver_up_manage.ver_cur_id
     *
     * @mbg.generated
     */
    public Integer getVerCurId() {
        return verCurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_up_manage.ver_cur_id
     *
     * @param verCurId the value for ver_up_manage.ver_cur_id
     *
     * @mbg.generated
     */
    public void setVerCurId(Integer verCurId) {
        this.verCurId = verCurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_up_manage.model_id
     *
     * @return the value of ver_up_manage.model_id
     *
     * @mbg.generated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_up_manage.model_id
     *
     * @param modelId the value for ver_up_manage.model_id
     *
     * @mbg.generated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_up_manage.vehicle_id
     *
     * @return the value of ver_up_manage.vehicle_id
     *
     * @mbg.generated
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_up_manage.vehicle_id
     *
     * @param vehicleId the value for ver_up_manage.vehicle_id
     *
     * @mbg.generated
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_manage
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VerUpManage other = (VerUpManage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStatusUpgrade() == null ? other.getStatusUpgrade() == null : this.getStatusUpgrade().equals(other.getStatusUpgrade()))
            && (this.getVerCurId() == null ? other.getVerCurId() == null : this.getVerCurId().equals(other.getVerCurId()))
            && (this.getModelId() == null ? other.getModelId() == null : this.getModelId().equals(other.getModelId()))
            && (this.getVehicleId() == null ? other.getVehicleId() == null : this.getVehicleId().equals(other.getVehicleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_manage
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStatusUpgrade() == null) ? 0 : getStatusUpgrade().hashCode());
        result = prime * result + ((getVerCurId() == null) ? 0 : getVerCurId().hashCode());
        result = prime * result + ((getModelId() == null) ? 0 : getModelId().hashCode());
        result = prime * result + ((getVehicleId() == null) ? 0 : getVehicleId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_up_manage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", statusUpgrade=").append(statusUpgrade);
        sb.append(", verCurId=").append(verCurId);
        sb.append(", modelId=").append(modelId);
        sb.append(", vehicleId=").append(vehicleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}