package com.ccclubs.pub.orm.model;

import java.io.Serializable;

public class VerUpgrade implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.soft_ver_id
     *
     * @mbg.generated
     */
    private Integer softVerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.hard_ver_id
     *
     * @mbg.generated
     */
    private Integer hardVerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.model_id
     *
     * @mbg.generated
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.tel_type
     *
     * @mbg.generated
     */
    private Integer telType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.tel_model
     *
     * @mbg.generated
     */
    private String telModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.inner_ver
     *
     * @mbg.generated
     */
    private String innerVer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.is_open
     *
     * @mbg.generated
     */
    private Byte isOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.des
     *
     * @mbg.generated
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.up_ver_no
     *
     * @mbg.generated
     */
    private String upVerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.ser_ftp_id
     *
     * @mbg.generated
     */
    private Integer serFtpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.per_timeout
     *
     * @mbg.generated
     */
    private Integer perTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.per_max_vehicle
     *
     * @mbg.generated
     */
    private Integer perMaxVehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_upgrade.turn_off_flag
     *
     * @mbg.generated
     */
    private Byte turnOffFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.id
     *
     * @return the value of ver_upgrade.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.id
     *
     * @param id the value for ver_upgrade.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.soft_ver_id
     *
     * @return the value of ver_upgrade.soft_ver_id
     *
     * @mbg.generated
     */
    public Integer getSoftVerId() {
        return softVerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.soft_ver_id
     *
     * @param softVerId the value for ver_upgrade.soft_ver_id
     *
     * @mbg.generated
     */
    public void setSoftVerId(Integer softVerId) {
        this.softVerId = softVerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.hard_ver_id
     *
     * @return the value of ver_upgrade.hard_ver_id
     *
     * @mbg.generated
     */
    public Integer getHardVerId() {
        return hardVerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.hard_ver_id
     *
     * @param hardVerId the value for ver_upgrade.hard_ver_id
     *
     * @mbg.generated
     */
    public void setHardVerId(Integer hardVerId) {
        this.hardVerId = hardVerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.model_id
     *
     * @return the value of ver_upgrade.model_id
     *
     * @mbg.generated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.model_id
     *
     * @param modelId the value for ver_upgrade.model_id
     *
     * @mbg.generated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.tel_type
     *
     * @return the value of ver_upgrade.tel_type
     *
     * @mbg.generated
     */
    public Integer getTelType() {
        return telType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.tel_type
     *
     * @param telType the value for ver_upgrade.tel_type
     *
     * @mbg.generated
     */
    public void setTelType(Integer telType) {
        this.telType = telType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.tel_model
     *
     * @return the value of ver_upgrade.tel_model
     *
     * @mbg.generated
     */
    public String getTelModel() {
        return telModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.tel_model
     *
     * @param telModel the value for ver_upgrade.tel_model
     *
     * @mbg.generated
     */
    public void setTelModel(String telModel) {
        this.telModel = telModel == null ? null : telModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.inner_ver
     *
     * @return the value of ver_upgrade.inner_ver
     *
     * @mbg.generated
     */
    public String getInnerVer() {
        return innerVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.inner_ver
     *
     * @param innerVer the value for ver_upgrade.inner_ver
     *
     * @mbg.generated
     */
    public void setInnerVer(String innerVer) {
        this.innerVer = innerVer == null ? null : innerVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.is_open
     *
     * @return the value of ver_upgrade.is_open
     *
     * @mbg.generated
     */
    public Byte getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.is_open
     *
     * @param isOpen the value for ver_upgrade.is_open
     *
     * @mbg.generated
     */
    public void setIsOpen(Byte isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.des
     *
     * @return the value of ver_upgrade.des
     *
     * @mbg.generated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.des
     *
     * @param des the value for ver_upgrade.des
     *
     * @mbg.generated
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.up_ver_no
     *
     * @return the value of ver_upgrade.up_ver_no
     *
     * @mbg.generated
     */
    public String getUpVerNo() {
        return upVerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.up_ver_no
     *
     * @param upVerNo the value for ver_upgrade.up_ver_no
     *
     * @mbg.generated
     */
    public void setUpVerNo(String upVerNo) {
        this.upVerNo = upVerNo == null ? null : upVerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.ser_ftp_id
     *
     * @return the value of ver_upgrade.ser_ftp_id
     *
     * @mbg.generated
     */
    public Integer getSerFtpId() {
        return serFtpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.ser_ftp_id
     *
     * @param serFtpId the value for ver_upgrade.ser_ftp_id
     *
     * @mbg.generated
     */
    public void setSerFtpId(Integer serFtpId) {
        this.serFtpId = serFtpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.per_timeout
     *
     * @return the value of ver_upgrade.per_timeout
     *
     * @mbg.generated
     */
    public Integer getPerTimeout() {
        return perTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.per_timeout
     *
     * @param perTimeout the value for ver_upgrade.per_timeout
     *
     * @mbg.generated
     */
    public void setPerTimeout(Integer perTimeout) {
        this.perTimeout = perTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.per_max_vehicle
     *
     * @return the value of ver_upgrade.per_max_vehicle
     *
     * @mbg.generated
     */
    public Integer getPerMaxVehicle() {
        return perMaxVehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.per_max_vehicle
     *
     * @param perMaxVehicle the value for ver_upgrade.per_max_vehicle
     *
     * @mbg.generated
     */
    public void setPerMaxVehicle(Integer perMaxVehicle) {
        this.perMaxVehicle = perMaxVehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.file_name
     *
     * @return the value of ver_upgrade.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.file_name
     *
     * @param fileName the value for ver_upgrade.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_upgrade.turn_off_flag
     *
     * @return the value of ver_upgrade.turn_off_flag
     *
     * @mbg.generated
     */
    public Byte getTurnOffFlag() {
        return turnOffFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_upgrade.turn_off_flag
     *
     * @param turnOffFlag the value for ver_upgrade.turn_off_flag
     *
     * @mbg.generated
     */
    public void setTurnOffFlag(Byte turnOffFlag) {
        this.turnOffFlag = turnOffFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VerUpgrade other = (VerUpgrade) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSoftVerId() == null ? other.getSoftVerId() == null : this.getSoftVerId().equals(other.getSoftVerId()))
            && (this.getHardVerId() == null ? other.getHardVerId() == null : this.getHardVerId().equals(other.getHardVerId()))
            && (this.getModelId() == null ? other.getModelId() == null : this.getModelId().equals(other.getModelId()))
            && (this.getTelType() == null ? other.getTelType() == null : this.getTelType().equals(other.getTelType()))
            && (this.getTelModel() == null ? other.getTelModel() == null : this.getTelModel().equals(other.getTelModel()))
            && (this.getInnerVer() == null ? other.getInnerVer() == null : this.getInnerVer().equals(other.getInnerVer()))
            && (this.getIsOpen() == null ? other.getIsOpen() == null : this.getIsOpen().equals(other.getIsOpen()))
            && (this.getDes() == null ? other.getDes() == null : this.getDes().equals(other.getDes()))
            && (this.getUpVerNo() == null ? other.getUpVerNo() == null : this.getUpVerNo().equals(other.getUpVerNo()))
            && (this.getSerFtpId() == null ? other.getSerFtpId() == null : this.getSerFtpId().equals(other.getSerFtpId()))
            && (this.getPerTimeout() == null ? other.getPerTimeout() == null : this.getPerTimeout().equals(other.getPerTimeout()))
            && (this.getPerMaxVehicle() == null ? other.getPerMaxVehicle() == null : this.getPerMaxVehicle().equals(other.getPerMaxVehicle()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getTurnOffFlag() == null ? other.getTurnOffFlag() == null : this.getTurnOffFlag().equals(other.getTurnOffFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSoftVerId() == null) ? 0 : getSoftVerId().hashCode());
        result = prime * result + ((getHardVerId() == null) ? 0 : getHardVerId().hashCode());
        result = prime * result + ((getModelId() == null) ? 0 : getModelId().hashCode());
        result = prime * result + ((getTelType() == null) ? 0 : getTelType().hashCode());
        result = prime * result + ((getTelModel() == null) ? 0 : getTelModel().hashCode());
        result = prime * result + ((getInnerVer() == null) ? 0 : getInnerVer().hashCode());
        result = prime * result + ((getIsOpen() == null) ? 0 : getIsOpen().hashCode());
        result = prime * result + ((getDes() == null) ? 0 : getDes().hashCode());
        result = prime * result + ((getUpVerNo() == null) ? 0 : getUpVerNo().hashCode());
        result = prime * result + ((getSerFtpId() == null) ? 0 : getSerFtpId().hashCode());
        result = prime * result + ((getPerTimeout() == null) ? 0 : getPerTimeout().hashCode());
        result = prime * result + ((getPerMaxVehicle() == null) ? 0 : getPerMaxVehicle().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getTurnOffFlag() == null) ? 0 : getTurnOffFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_upgrade
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", softVerId=").append(softVerId);
        sb.append(", hardVerId=").append(hardVerId);
        sb.append(", modelId=").append(modelId);
        sb.append(", telType=").append(telType);
        sb.append(", telModel=").append(telModel);
        sb.append(", innerVer=").append(innerVer);
        sb.append(", isOpen=").append(isOpen);
        sb.append(", des=").append(des);
        sb.append(", upVerNo=").append(upVerNo);
        sb.append(", serFtpId=").append(serFtpId);
        sb.append(", perTimeout=").append(perTimeout);
        sb.append(", perMaxVehicle=").append(perMaxVehicle);
        sb.append(", fileName=").append(fileName);
        sb.append(", turnOffFlag=").append(turnOffFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}